### ISSUE TITLE
Plans for an SCSS version/conversion?

### ISSUE THREAD

**Issue by jordanbrauer** [andrewgioia/Keyrune#10]
I know this isn't an issue exactly, but I ask because SASS/SCSS has become a lot more popular than LESS. 

If you are planing on doing this, do you need hand?

**Comment by andrewgioia** [comment]
@jordanbrauer yeah it's been on the general to-do forever but I'd love a hand, that'd be fantastic. Definitely feel free to start a branch for it if you're interested, otherwise I'd say the timeline would be a few weeks if it's something you all want quicker.

**Comment by jordanbrauer** [comment]
@andrewgioia very cool! I think I may do just that. I have never worked with fonts before though, so this will be a fun endeavor. I am pretty handy with CSS/SCSS however, so I don't think I will have too much trouble. Part of the reason I want to help is that I plan to use your font in a project ;).

**Comment by jordanbrauer** [comment]
@andrewgioia I have started work on the SCSS version. :)

**Comment by jordanbrauer** [comment]
Sass code has been pulled into master. Closing this issue now.
