### ISSUE TITLE
New Icon: Game Night 2019

### ISSUE THREAD

**Issue by arjenbrandenburgh** [andrewgioia/Keyrune#102]
Couldn't find a higher resolution image yet.

[Example card](https://img.scryfall.com/cards/large/front/e/c/ecbeac44-9392-4522-8ff5-87079386bd0a.jpg)

**Comment by csuhta** [comment]
Here's a trace by the Scryfall team:
[gn2.svg.zip](https://github.com/andrewgioia/Keyrune/files/3787203/gn2.svg.zip)

**Comment by arjenbrandenburgh** [comment]
<3 @csuhta

**Comment by andrewgioia** [comment]
Thanks as always @csuhta and the scryfall team, really appreciated.

Added in 3.6.0.
