### ISSUE TITLE
Ikoria Commander Decks (C20)

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/Keyrune#103]
One of the 2020 sets announced yesterday at https://magic.wizards.com/en/articles/archive/news/big-things-are-coming-commander-2020-2019-10-30.

Set code is confirmed to be C20 and will be 5 new commander decks during Ikoria. No symbol previewed yet.

**Comment by fenhl** [comment]
The symbol has been previewed [in the announcement video at 2m56s](https://youtube.com/watch?v=T1ncWcr7Pks&t=2m56s).

**Comment by andrewgioia** [comment]
Added in 3.6.2
