### ISSUE TITLE
Historic Anthology 1

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#108]
An update to MTG Arena which just released introduced the set *Historic Anthology 1*. Even though the cards show set symbols of previous sets in which they were printed, the set does have its own expansion symbol, as can be seen in the collection viewer:

![screenshot of the MTG Arena collection viewer's advanced filters](https://user-images.githubusercontent.com/641386/69362421-6356b800-0c86-11ea-9648-b054f27fd451.png)

Note the black square in the background which seems to be part of the symbol, although I'm not sure if it's possible to represent it in a monochrome font.

**Comment by andrewgioia** [comment]
Thanks for the screenshot @fenhl. I wish they would stop including backgrounds like that in set symbols and you're right, it won't be possible to do with the current 1 tone glyphs. I will definitely add this symbol though, probably as `ha1` unless it indicates something else.

If they are going to be doing a lot of Arena-only sets we could also prefix it as `aha1` or something.

**Comment by andrewgioia** [comment]
Added in 3.6.3 and SVG included in that release: https://github.com/andrewgioia/Keyrune/blob/master/svg/ha1.svg
