### ISSUE TITLE
Secret Lair Drop Series (SLD)

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#109]
The Secret Lair Drop Series has the set code SLD and the same symbol as PMEI. 

HTR also has the same symbol by the way I think this keyrune was duplicated.

Here are the examples from Scryfall:
HTR: https://scryfall.com/card/htr17/1/diabolical-salvation
SLD: https://scryfall.com/card/sld/5/snow-covered-forest
PMEI: https://scryfall.com/card/pmei/33/ja/lava-coil

**Comment by andrewgioia** [comment]
Thanks @yandere-sliver, I can alias those sets using the PMEI symbol.

Also I'm not sure what you mean by "HTR also has the same symbol by the way I think this keyrune was duplicated." Is there an issue with the font or are you saying that they all just use the same symbol?

**Comment by andrewgioia** [comment]
This is updated now but I'm realizing not only are there additional HTR sets with the same icon, there are a ton of other small-print promo "sets" on Scryfall that use this and other promo symbols.

I think I'm going to separate out all the aliases from the primary icons file to handle this in the next update.
