### ISSUE TITLE
Request: Kaladesh Inventions icon

### ISSUE THREAD

**Issue by askinley** [andrewgioia/Keyrune#11]
Here's the highest resolution image I could find for it:

![](http://gatherer.wizards.com/Handlers/Image.ashx?type=symbol&set=MPS_KLD&size=large&rarity=S)

**Comment by andrewgioia** [comment]
@askinley thank you! That should be good to trace and I'll add this today.

**Comment by andrewgioia** [comment]
@askinley This is be added now: https://github.com/andrewgioia/Keyrune/commit/5489b5181fe7e19b6ad22d5b0f550c817b0182b1

When the icon is scaled down to 16px it looks it bit difficult to make out the curls, I'll have to make those a bit thinner soon when I have some more time. That's a bit of a nitpick though and this should be good to use now.
