### ISSUE TITLE
Theros: Beyond Death has wrong code

### ISSUE THREAD

**Issue by dekoza** [andrewgioia/Keyrune#111]
Code for `Theros: Beyond Death` should be TBD, not THB.

**Comment by fenhl** [comment]
What's your source on this?

**Comment by fenhl** [comment]
If you look at the bottom left of a card from *Theros Beyond Death* (no colon btw), you'll see the set code THB.

**Comment by dekoza** [comment]
I stand corrected. During spoiler season scryfall somehow had the codeTBD. Closing.
