### ISSUE TITLE
C14 and Lorwyn have the same UTF8 unicode representations

### ISSUE THREAD

**Issue by gabespace** [andrewgioia/Keyrune#114]
In the cheat sheet [here](https://andrewgioia.github.io/Keyrune/cheatsheet.html), the UTF8 representations of the unicode symbols for C14 and Lorwyn are identical. They're both `&#xe63d;`.

**Comment by andrewgioia** [comment]
Thanks for the heads up! Github is having some issues right now but this is corrected in the cheatsheet and it'll show up soon online.
