### ISSUE TITLE
Mystery Booster symbol missing

### ISSUE THREAD

**Issue by juicemtg** [andrewgioia/Keyrune#120]

**Comment by fenhl** [comment]
Does Mystery Booster even have its own expansion symbol? The playtest cards don't have a symbol, and all the other cards are printed with their original symbol.

**Comment by juicemtg** [comment]
They use this symbol  in the bottom right of every card to distinguish it from the rest, so it would be nice to have this symbol as an icon to recognize them as the Mystery Booster. Thanks! Eric From: FenhlSent: Friday, May 15, 2020 3:45 PMTo: andrewgioia/KeyruneCc: juicemtg; AuthorSubject: Re: [andrewgioia/Keyrune] Mystery Booster symbol missing (#120) Does Mystery Booster even have its own expansion symbol? The playtest cards don't have a symbol, and all the other cards are printed with their original symbol.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by csuhta** [comment]
The symbol in the bottom left of MB1 cards is just the planewalker symbol, which is available in the other project: https://andrewgioia.github.io/Mana/icons.html

**Comment by juicemtg** [comment]
Thank you. I didn’t know this project existed. I appreciate you letting me know. 

Thanks,

Eric
