### ISSUE TITLE
Core 2021 (M21) and Jumpstart

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#123]
Apparently Wizards pulled a bait and switch on us. 

The symbol with the 2 cards overlapped which we thought was the Core 2021 symbol belong to Jumpstart instead.
Jumpstart will be released with M21 and we don't know the set code yet.

Core 2021 will use the typical M21. Even with the low quality image it should be easy to construct. Take the M20 rune and replace the 0 with a 1 that can be taken from M19.

![M21](https://user-images.githubusercontent.com/25598912/83723327-6ae41a00-a636-11ea-805c-e857c7ace424.png)

**Comment by yandere-sliver** [comment]
Actually here is a nice large version
![M21_set_symbol](https://user-images.githubusercontent.com/25598912/83771111-d9969700-a679-11ea-98e2-c7a259563051.png)

**Comment by csuhta** [comment]
Here are traces for M21 and Jumpstart!

https://img.scryfall.com/sets/m21.svg
https://img.scryfall.com/sets/jmp.svg

The WPN materials for Jumpstart seem to be using JMP as the set code, but that is not on any public articles so it could be subject to change: 

![image-1](https://user-images.githubusercontent.com/769083/83811694-49ac1980-a688-11ea-9c7b-cedc0966ca72.png)

**Comment by andrewgioia** [comment]
Both are in 3.6.6
