### ISSUE TITLE
Signature Spellbook: Chandra (SS3)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#124]
Images for this set are still poor, but here's what we ended up with:
http://img.scryfall.com/sets/ss3.svg

**Comment by andrewgioia** [comment]
Very much appreciated at always @csuhta. It looks like WPN has this one on their marketing page, I did a trace here if you're interested: https://github.com/andrewgioia/Keyrune/blob/master/svg/ss3.svg
