### ISSUE TITLE
Typo in Unsanctioned listing on Set Symbol Icons page

### ISSUE THREAD

**Issue by linc** [andrewgioia/keyrune#126]
https://andrewgioia.github.io/Keyrune/icons.html?icon=und

The main-page listing incorrectly lists the abbreviation for Unsanctioned as `ust` instead of `und`. (The click-thru is correct.)

<img width="242" alt="Screen Shot 2020-06-18 at 10 31 41 PM" src="https://user-images.githubusercontent.com/117672/85090699-c1636380-b1b3-11ea-82ff-9bb16e14db8a.png">

**Comment by andrewgioia** [comment]
Thanks @linc! This is not updated.
