### ISSUE TITLE
Add planeswalker symbol

### ISSUE THREAD

**Issue by jdkoren** [andrewgioia/Keyrune#127]
This could be added among the "unofficial" symbols.

<img width="300" alt="planeswalker_symbol" src="https://user-images.githubusercontent.com/771156/86430036-128c5080-bca6-11ea-95c1-da206ceffb03.png" />

**Comment by csuhta** [comment]
This symbol is available in the sister project: https://andrewgioia.github.io/Mana/icons.html

**Comment by jdkoren** [comment]
> This symbol is available in the sister project: https://andrewgioia.github.io/Mana/icons.html

Ah, did not know that. Thanks
