### ISSUE TITLE
Support documentation not accessible

### ISSUE THREAD

**Issue by levi-wilson** [andrewgioia/keyrune#128]
The https://andrewgioia.github.io/Keyrune/cheatsheet.html pages are no longer available.

**Comment by fenhl** [comment]
It's apparently been moved to <https://keyrune.andrewgioia.com/cheatsheet.html>.

**Comment by andrewgioia** [comment]
Sorry about this @levi-wilson, yes I changed the domain but the original URLs should 301 to the new one and the assets should be loading correctly. If you're getting any errors still could you comment on this?

**Comment by levi-wilson** [comment]
> Sorry about this @levi-wilson, yes I changed the domain but the original URLs should 301 to the new one and the assets should be loading correctly. If you're getting any errors still could you comment on this?

Yes when i try to go to the pages that i bookmarked i would get this error.

404
There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

GitHub Status — @githubstatus
