### ISSUE TITLE
Create aliases of PMEI for Secret Lair sets

### ISSUE THREAD

**Issue by kodabb** [andrewgioia/keyrune#131]
would it be possible to add a shooting star for the pre-judge academy judge promos?

possibly related to #118

**Comment by csuhta** [comment]
The star is PMEI in this project https://keyrune.andrewgioia.com/icons.html?icon=pmei

**Comment by kodabb** [comment]
oh interesting thanks for pointing it out, i'll use it in the meantime

**Comment by kodabb** [comment]
it looks like secret lair _promos_ and magic fest sets are affected, so possibly a few more aliases should be added, like for https://github.com/andrewgioia/Keyrune/issues/109

**Comment by yandere-sliver** [comment]
SLU and SLD would be the two codes for Secret Lair

**Comment by andrewgioia** [comment]
Both aliases as well as `.psld` are in 3.6.7
