### ISSUE TITLE
[AKR] Amonkhet Remastered

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#132]
There's a new MTGA set.

The best image I could find on the internet.

![image-3](https://user-images.githubusercontent.com/4212200/90318771-1fd56580-df09-11ea-93f6-da3f9afaf69d.png)

**Comment by csuhta** [comment]
Here's our trace! http://c2.scryfall.com/file/scryfall-symbols/sets/akr.svg

**Comment by andrewgioia** [comment]
Added in 3.6.7!
