### ISSUE TITLE
[xDND] Dungeons & Dragons: Adventures in the Forgotten Realms

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/keyrune#137]
Unknown set code

Announced today via Magic Twitch stream:

<img width="167" alt="DnD Adventures in the Forgotten Realms" src="https://user-images.githubusercontent.com/221473/91895247-e91b8100-ec64-11ea-9599-07124d469324.png">

**Comment by csuhta** [comment]
[xdnd.svg.zip](https://github.com/andrewgioia/keyrune/files/5161702/xdnd.svg.zip)

**Comment by andrewgioia** [comment]
Added in 3.7.0
