### ISSUE TITLE
[TSR] Time Spiral Remastered

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/keyrune#138]
Unknown set code, will probably use xTSR until announced

<img width="169" alt="Time Spiral Remastered" src="https://user-images.githubusercontent.com/221473/91895311-081a1300-ec65-11ea-9b22-3287d8d9fc2d.png">

**Comment by csuhta** [comment]
Here's our trace: https://c2.scryfall.com/file/scryfall-symbols/sets/tsr.svg

**Comment by andrewgioia** [comment]
Added in 3.7.0
