### ISSUE TITLE
Any CDN that can be used?

### ISSUE THREAD

**Issue by stash86** [andrewgioia/Keyrune#14]
Hi,

I just want to know whether you have submitted this project to any CDN hosting?

Thanks

**Comment by dgant** [comment]
You may be able to use the GitHub file URL in a pinch.

**Comment by mikegioia** [comment]
https://cdnjs.com/libraries/clndr

**Comment by mikegioia** [comment]
I think it would be possible to add to CDNJS, I had to do it for another project and now it's automated.

**Comment by tdbear** [comment]
pretty please...

**Comment by andrewgioia** [comment]
Currently testing jsdelivr to host the project on their CDN. I submitted a PR and am awaiting approval, hopefully we can use them.

**Comment by andrewgioia** [comment]
@stash86 @dgant @tdbear @mikegioia We're live on jsDelivr! I'll update the readme with information on how to use it but for those following this issue:

* The project is hosted at `cdn.jsdelivr.net` and files are referenced as http://cdn.jsdelivr.net/keyrune/{version}/{file}; in the current case the files will be at http://cdn.jsdelivr.net/keyrune/2.2.0/ (for instance)
* jsDelivr apparently doesn't maintain directory structures so the CSS and font files are all in the version directories
* You can reference the files in your project as //cdn.jsdelivr.net/keyrune/2.2.0/keyrune.min.css and //cdn.jsdelivr.net/keyrune/2.2.0/keyrune.eot, etc. Increment the version number whenever you want to update to the latest or newer version of Keyrune.
* Updates generally take about 20 minutes to go live on the CDN from when they're pushed to Keyrune (judging by this first commit).

Here are the files on jsDelivr's repository, for reference: https://github.com/jsdelivr/jsdelivr/tree/master/files/keyrune

Thanks for you patience guys! Please report any issues or delays with the CDN as we get started with it.
