### ISSUE TITLE
[xIN3] Innistrad Vampires

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/keyrune#140]
Unknown set code, will probably use xIN3

<img width="123" alt="Innistrad Vampires" src="https://user-images.githubusercontent.com/221473/91895440-444d7380-ec65-11ea-86b2-110b359beb77.png">

**Comment by csuhta** [comment]
Here's our trace!
[xin3.svg.zip](https://github.com/andrewgioia/keyrune/files/5161698/xin3.svg.zip)

**Comment by andrewgioia** [comment]
Added in 3.7.0
