### ISSUE TITLE
[xIN4] Innistrad Werewolves

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/keyrune#141]
Unknown set code, will probably use xIN4 until announced

<img width="115" alt="Innistrad Werewolves" src="https://user-images.githubusercontent.com/221473/91895499-56c7ad00-ec65-11ea-98f3-98a9d65f86ea.png">

**Comment by csuhta** [comment]
Here's our trace! 
[xin4.svg.zip](https://github.com/andrewgioia/keyrune/files/5161700/xin4.svg.zip)

**Comment by andrewgioia** [comment]
Added in 3.7.0
