### ISSUE TITLE
[ZNE] Zendikar Rising Expeditions

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/keyrune#142]
Expeditions are back and they have an extra set code and icon.

![znr-1-flooded-strand](https://user-images.githubusercontent.com/25598912/91903182-18e97980-eca3-11ea-8979-fa0655dc66e2.jpg)

**Comment by csuhta** [comment]
Here's our trace! https://c2.scryfall.com/file/scryfall-symbols/sets/zne.svg

**Comment by andrewgioia** [comment]
Thanks @csuhta for this and the other ones, it's a massive help and I really appreciate it.

Added in 3.7.0.
