### ISSUE TITLE
Great idea -- I just can't get the font to render in Photoshop or Illustrator. Any tips?

### ISSUE THREAD

**Issue by mediareason** [andrewgioia/Keyrune#15]
I'm totally stumped. The typeface installs into Font Book just fine, even shows up in autocomplete in PS/IA, but isn't selectable and doesn't show up in the drop down pick list.

**Comment by andrewgioia** [comment]
@mediareason Even though you installed the font to your system, you'll need to copy and paste the glyphs from the [cheatsheet page](https://andrewgioia.github.io/Keyrune/cheatsheet.html) to use them in a desktop app (like PS or Word). When you paste them the Keyrune font should come through, but if not just highlight the character in PS and change the font to Keyrune.

Keyrune uses the [private use area](https://en.wikipedia.org/wiki/Private_Use_Areas) range of code points in Unicode so you won't be able to just type characters when selecting the font, like you would with Times New Roman, etc.
