### ISSUE TITLE
Kaladesh Remastered (KLR)

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/keyrune#151]
Here are the cards and also the icon.
https://magic.wizards.com/en/articles/archive/card-image-gallery/kaladesh-remastered

This is quite low quality but again a combination of the two original icons. at a later time point one can attempt to rip the icon from the client.

**Comment by Razviar** [comment]
Here's rips
![ExpansionSymbol_KLR_Common](https://user-images.githubusercontent.com/29640542/98785442-453d1700-2405-11eb-87ed-c06641d8dc10.png)
![ExpansionSymbol_KLR_Mythic](https://user-images.githubusercontent.com/29640542/98785444-45d5ad80-2405-11eb-96d7-cbf59b943416.png)
![ExpansionSymbol_KLR_Rare](https://user-images.githubusercontent.com/29640542/98785445-45d5ad80-2405-11eb-9f7a-9caf9c3508b9.png)
![ExpansionSymbol_KLR_Uncommon](https://user-images.githubusercontent.com/29640542/98785446-466e4400-2405-11eb-9918-fb622bfbe485.png)

**Comment by andrewgioia** [comment]
Thanks @yandere-sliver, this was very close to Kaladesh's symbol fortunately as well. I have it drawn and ready to go in the release today most likely.

**Comment by andrewgioia** [comment]
Added in 3.7.1
