### ISSUE TITLE
Archie (J20) is outlined incorrectly when rarity gradient is enabled

### ISSUE THREAD

**Issue by scarletcs** [andrewgioia/keyrune#155]
Archie on the J20 gift cards looks like this:

![2021-02-13_16-49-35_firefox](https://user-images.githubusercontent.com/4585677/107855644-8e916e00-6e1b-11eb-82b1-f322dd0b43bd.png)

He's replicated fine with rarity gradient off. The hollow strokes here match the black strokes seen in his symol on the card.

![2021-02-13_16-49-20_firefox](https://user-images.githubusercontent.com/4585677/107855641-8df8d780-6e1b-11eb-83e2-4280ac156577.png)

But when rarity gradient is on, the solid shapes get outlines that don't correspond to anything we see on the card, and which doesn't look great due to weird gaps appearing.

![2021-02-13_16-49-22](https://user-images.githubusercontent.com/4585677/107855643-8e916e00-6e1b-11eb-9f8f-17afb929693d.png)

At a small size (left; original featured on cards on the right) it's close but still not quite there, since the gaps make the outlines appear faded, and Archie has hollow eyes/beak instead of them being filled in.

![2021-02-13_16-54-22_firefox](https://user-images.githubusercontent.com/4585677/107855760-21caa380-6e1c-11eb-8786-6feb2e058da8.png) ![2021-02-13_16-53-50_firefox](https://user-images.githubusercontent.com/4585677/107855755-17100e80-6e1c-11eb-9aee-ab25250817f1.png)

(Actual Archie images from [Arena Rector](https://scryfall.com/card/j20/1/arena-rector))

**Comment by andrewgioia** [comment]
I didn't realize this was related to the CSS outlining "hack", the true fix is to make this a multi-layered SVG which will push it to 4.0. The outline for now is just a convenience class and due to the nature of how it's done via CSS I unfortunately can't fix this one until we use 2 layered SVGs.
