### ISSUE TITLE
[STX] Strixhaven Mystical Archive

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/keyrune#156]
Here's the symbol :D 
[STA_symbol.svg.zip](https://github.com/andrewgioia/keyrune/files/6039424/STA_symbol.svg.zip)

![sta-10-swords-to-plowshares](https://user-images.githubusercontent.com/769083/109079361-d7bfa880-76cc-11eb-922e-02954670143b.jpg)

**Comment by andrewgioia** [comment]
Really sorry how long this one took, finally up as of 3.8.0 now
