### ISSUE TITLE
Cannot clone repository on Windows

### ISSUE THREAD

**Issue by flibX0r** [andrewgioia/keyrune#158]
I couldn't find an existing issue about this.

You cannot fully clone this repository on a Windows system because the Conflux SVG (svg/con.svg) uses a reserved filename (CON)
See the full list of reserved names on this page: https://docs.microsoft.com/en-au/windows/win32/fileio/naming-a-file

As far as I'm aware, the only possible fix is to change the filename. Windows ignores the file extension, so a prefix or postfix would work.

**Comment by ruipires** [comment]
I experienced the same issue (checkout on WSL was a viable workaround for me).
@andrewgioia are you interested in a pull request to fix this ?

**Comment by andrewgioia** [comment]
Sorry for the lack of response here, wow I had no idea about that name collision issue with Windows. Does it just not download or extract the file?

I think the only solution is to rename it like you said, I'll have to add an underscore to the end or something.

**Comment by ruipires** [comment]
> Sorry for the lack of response here, wow I had no idea about that name collision issue with Windows. Does it just not download or extract the file?
> 
> I think the only solution is to rename it like you said, I'll have to add an underscore to the end or something.

It (windows) will just fail when creating the file (with one of those restricted names).
Doesn't matter if its the user or a program, those names are restricted.


Quoting from the document @flibX0r  mentioned:
> Do not use the following reserved names for the name of a file:
> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9

**Comment by andrewgioia** [comment]
I forgot to make this change in the latest release today but did push up the name change in master currently (underscore at the end of the set code). The next time I publish a release this will be good to go there.
