### ISSUE TITLE
KHC symbol missing on Keyrune site

### ISSUE THREAD

**Issue by spacemonaut** [andrewgioia/keyrune#160]
While the KHC set symbol appears to have been added in #152, the set symbol is missing [on the Keyrune site's Set Symbol Icons page](https://keyrune.andrewgioia.com/icons.html?icon=khc) and is showing up as just the standard (M) instead:

![2021-03-27_14-52-53_firefox](https://user-images.githubusercontent.com/4585677/112724638-39fa0c00-8f0c-11eb-8dca-3ad4f10077db.png)

Possibly not just a typo in the layout:

![2021-03-27_14-54-38_firefox](https://user-images.githubusercontent.com/4585677/112724668-61e96f80-8f0c-11eb-97e7-8fd5fde183ce.png)

**Comment by andrewgioia** [comment]
Sorry @spacemonaut this should be fixed now, it was an issue with the CDN url pointing to the wrong version of Keyrune. I have this fixed now and going forward it should never be an issue.
