### ISSUE TITLE
[C21] Commander 2021

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/keyrune#161]
Here's our trace:
[c21.svg.zip](https://github.com/andrewgioia/keyrune/files/6261097/c21.svg.zip)

![c21-234-arcane-signet](https://user-images.githubusercontent.com/769083/113639415-21de6700-9647-11eb-9fe7-bb944156d588.jpg)

**Comment by andrewgioia** [comment]
Thanks @csuhta. This is in 3.8.0 now.
