### ISSUE TITLE
C21 & STA not displaying correctly

### ISSUE THREAD

**Issue by goosedeersolutions** [andrewgioia/keyrune#162]
The symbols for C21 and STA are not displaying correctly.

```
<link href="//cdn.jsdelivr.net/npm/keyrune@latest/css/keyrune.min.css" rel="stylesheet" type="text/css" />
<div class="button" tabindex="0" onclick="location.href='/magic/sets/c21';">
    <i class="icon ss ss-c21"></i>    
    ...
</div>
```

![image](https://user-images.githubusercontent.com/26407400/124722052-943e3c00-df01-11eb-9960-d13e4bf649ef.png)

**Comment by goosedeersolutions** [comment]
These icons seem to be back now.
![image](https://user-images.githubusercontent.com/26407400/124769983-db442580-df31-11eb-903c-92540ab5c304.png)

**Comment by andrewgioia** [comment]
Thanks @goosedeersolutions I think it may have to do with jsdelivr's caching when you use the @latest URI, just as an FYI
