### ISSUE TITLE
[AFC] Forgotten Realms Commander

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/keyrune#163]
AFC has a separate symbol that looks to be the AFR dragon face cut out of a commander shield symbol. Still looking for a high resolution scan or some version that isn't super tiny.

**Comment by 4eveRS** [comment]
The best reference image I could find :)
![afc_reference](https://user-images.githubusercontent.com/4212200/125683813-8037c28c-7e1c-407d-8bfa-32787bc09be4.PNG)

**Comment by andrewgioia** [comment]
Awesome that's perfect, where did you find that if you mind sharing? I looked extensively and couldn't find anything better than the low resolution preview cards.

**Comment by andrewgioia** [comment]
Added in 3.8.2 just now

**Comment by 4eveRS** [comment]
Hey, I found it looking for the Commanders deck on Amazon.

Here's the [Amazon Link](https://www.amazon.com/Magic-Gathering-Adventures-Forgotten-Commander/dp/B093CJWSN7).
