### ISSUE TITLE
No symbols in the font

### ISSUE THREAD

**Issue by lambslamchops** [andrewgioia/keyrune#165]
Whenever I try to install the font it only shows these two symbols and nothing else, if I try to use the cheatsheet all the symbols paste as "?" or just a blank square.
<img width="393" alt="Screen Shot 2021-08-06 at 11 33 19 AM" src="https://user-images.githubusercontent.com/88264737/128556493-8b51e2d9-f63b-4188-8d22-ed6475293447.png">

**Comment by andrewgioia** [comment]
@lambslamchops could you try uninstalling the font and reinstalling? it could have been an old version with an error in it.
