### ISSUE TITLE
Commander Collection Black

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#166]
Here's a high quality image of the newest Commander Collection.

![cc2](https://user-images.githubusercontent.com/4212200/130881689-b62a6205-df66-4839-899d-b03fd34e4336.png)

**Comment by csuhta** [comment]
Our trace: https://c2.scryfall.com/file/scryfall-symbols/sets/cc2.svg?1631505600

**Comment by andrewgioia** [comment]
Added in 3.8.4
