### ISSUE TITLE
Innistrad: Midnight Hunt Commander Icon

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#167]
A somewhat hi-res image of the set icon.

![midnight hunt commander](https://user-images.githubusercontent.com/4212200/134250442-cefbde27-2fae-4abf-badd-2fd7ad754ebb.PNG)

**Comment by csuhta** [comment]
Our trace: https://c2.scryfall.com/file/scryfall-symbols/sets/mic.svg?1632110400

**Comment by andrewgioia** [comment]
Added in 3.8.4
