### ISSUE TITLE
individuals SVG missing 

### ISSUE THREAD

**Issue by ArkadesSabboth** [andrewgioia/keyrune#168]
In the version 3.8.3, some set symbols are missing from the svg folder (but are in the font) :
- kaldheim, commander : khc 
- kaladesh remastered : klr 

Some files uses the alt name :
- kaldheim : xkld for khm
- strixhaven : xssm for stx

in keyrune.svg, at least three symbols have the wrong glyph-name (but the individuals svg have the right name) :
- adventures in the forgotten realms : xdnd for afr
- adventures in the forgotten realms (border) : xdnd-border  for afr-border 
- zendikar rising : xznr  for znr

**Comment by andrewgioia** [comment]
Fixed/added in 3.8.4
