### ISSUE TITLE
CDN not updated with MID icon

### ISSUE THREAD

**Issue by rconroy293** [andrewgioia/keyrune#170]
MID icons have been added in the source code, but the latest version on https://cdn.jsdelivr.net/npm/keyrune@latest/css/keyrune.css does not have MID data

**Comment by beheh** [comment]
While this has been fixed in `master` at 6e33b58eb92e252ce20dcce716995ac63407258f, there has not been a keyrune release since then.

@andrewgioia What do you think about publishing a new version, seeing as VOW is about to release?

**Comment by andrewgioia** [comment]
Should be fixed in 3.8.4
