### ISSUE TITLE
Unfinity (UNF)

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#175]
A new "unset" is going to be released on 2022-04-01, called Unfinity. 

Below is the best image I could find of its set icon.

![image](https://user-images.githubusercontent.com/4212200/144318190-b45f27a9-71b1-4c47-bfa3-517b1baf44c9.png)

**Comment by csuhta** [comment]
Here's our trace: https://c2.scryfall.com/file/scryfall-symbols/sets/unf.svg

**Comment by andrewgioia** [comment]
Added in v3.9.0
