### ISSUE TITLE
Alchemy: Innistrad (Y22)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/keyrune#176]
Set code: Y22 (Arena-only)
Example: https://c1.scryfall.com/file/scryfall-cards/large/front/c/2/c2744e16-1016-432a-8698-2a2d407e7b04.jpg?1638836474
Our trace: https://c2.scryfall.com/file/scryfall-symbols/sets/y22.svg

**Comment by andrewgioia** [comment]
Added in v3.9.0
