### ISSUE TITLE
Kamigawa: Neon Dynasty (NEO)

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#178]
![image](https://user-images.githubusercontent.com/4212200/146586029-7fff4bb2-a39a-4d76-8930-1a723afb59be.png)

**Comment by csuhta** [comment]
Here's our trace: https://c2.scryfall.com/file/scryfall-symbols/sets/neo.svg?1643000400

**Comment by andrewgioia** [comment]
Thanks @csuhta. This is now in v3.9.0.
