### ISSUE TITLE
Duel Decks: Mind vs. Might

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#18]
The expansion symbol can be seen on the [Coming Soon](http://magic.wizards.com/en/products/coming-soon) page of the Card Set Archive.

**Comment by andrewgioia** [comment]
Putting on hold as I waiting for a higher resolution version of this icon, perhaps on release day. I'll keep looking.

**Comment by csuhta** [comment]
Spoilers for this product have started. I know there isn't a giant version of the icon available yet, but I'm happy to try drawing a starter SVG for you again. 

Set packaging: http://magic.wizards.com/en/articles/archive/news/duel-decks-mind-vs-might-packaging-2017-03-10

Best picture I can find:

![dds_symbol](https://cloud.githubusercontent.com/assets/769083/23811176/daf0d2ee-05a2-11e7-8bfd-33fddcb8f171.png)

**Comment by andrewgioia** [comment]
Thanks @csuhta, I tried drawing this one from your reference a few times but haven't been happy with it yet. I'll keep at it but it's very small and I'm not confident I'm getting it exactly. I'm hoping Wizards releases an official symbol or that the MTGO client has it at some point.

**Comment by csuhta** [comment]
Here's my attempt if it's helpful. I see what you mean about this symbol being super tedious to reproduce.

[dds.svg.zip](https://github.com/andrewgioia/Keyrune/files/860346/dds.svg.zip)

**Comment by andrewgioia** [comment]
That's excellent @csuhta, thank you for contributing. I just made a few minor adjustments on the curves and spacing and pushed it up now.
