### ISSUE TITLE
Kamigawa Neon Dynasty Commander (NEC)

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#180]
**Example**

![image](https://user-images.githubusercontent.com/4212200/151500729-7f5ec115-198c-4f1c-b4ba-803fe679aa89.png)

**Set Code**: NEC

**Comment by csuhta** [comment]
Here's our trace: https://c2.scryfall.com/file/scryfall-symbols/sets/nec.svg?1643000400
