### ISSUE TITLE
[Request] Mana symbols

### ISSUE THREAD

**Issue by pakoito** [andrewgioia/keyrune#183]
I am contributing to an opensource MTG project called Forge that could benefit from embedding this font. What we're mostly missing from the current iteration of this font are the mana icons.

We have a reference of the ones we use: https://git.cardforge.org/core-developers/forge/-/blob/master/forge-gui/res/skins/default/sprite_manaicons.png and a couple that are coming: https://git.cardforge.org/core-developers/forge/-/blob/master/forge-gui/res/skins/default/sprite_phyrexian.png. I believe someone in the project is a vector virtuoso, so we could find SVGs if needed.

Many thanks and great project!

**Comment by csuhta** [comment]
There's a sister project for that: https://github.com/andrewgioia/mana
