### ISSUE TITLE
Streets of New Capenna [SNC] [NNC]

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#184]
### Streets of New Capenna (SNC)
![d723yTewed_SNC](https://user-images.githubusercontent.com/4212200/156895481-9188dc69-6f6d-4cc1-89cf-8c6eedc286a9.png)

### Streets of New Capenna Commander (NNC)
![d723yTewed_NCC](https://user-images.githubusercontent.com/4212200/156895489-62503c1c-efaf-4c64-97a8-7b857182f1cc.png)

**Comment by andrewgioia** [comment]
Thanks @4eveRS, could you let me know where you got such a high res version of the NNC logo? I'm curious if there's a source for these I'm not aware of.

**Comment by 4eveRS** [comment]
Hey @andrewgioia, I got these icons from a WOTC article published [here](https://magic.wizards.com/en/articles/archive/news/first-look-streets-new-capenna-where-family-means-business-2022-03-03). 

They've recently started to publish a series of articles at every new set announcement, and generally, these articles contain a high-res image of the set icons.

The article for streets of new capenna even includes a high-res image of each family (guild) involved in the set!

**Comment by andrewgioia** [comment]
Awesome thank you! I didn't realize they started including such high res versions of the symbols, I need to check their website more :P

**Comment by 4eveRS** [comment]
Yup. My bad it's actually NCC.
