### ISSUE TITLE
Commander Legends: Battle for Baldur's Gate [CLB]

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#186]
![cbl_8OlZuUVD9K](https://user-images.githubusercontent.com/4212200/160225255-0d372437-2665-4a42-908b-a5529479df63.png)

[Source - WOTC](https://magic.wizards.com/en/articles/archive/news/first-look-commander-legends-battle-baldurs-gate-2022-03-24)

**Comment by andrewgioia** [comment]
Thanks @4eveRS this is up in 3.9.2 now

**Comment by 4eveRS** [comment]
Hey, you're welcome @andrewgioia and thanks for the awesome library!

Just a heads up, there's a typo on the set class name on the CSS, you typed CBL instead of CLB😆

**Comment by andrewgioia** [comment]
Sorry about that @4eveRS this is now fixed
