### ISSUE TITLE
[Request] Create inner and outer for KHC symbol?

### ISSUE THREAD

**Issue by MrTeferi** [andrewgioia/keyrune#191]
Hi! I've been really enjoying having multiple elements split up for sets like NCC and MID, where there's an inner shape and an outer shape for example, since sometimes the inner shape is always white and the outer matches the rarity.

Any chance we could go back to the KHC symbol and separate the middle shape (kind of X-wing looking thing?) and the outer shield shape?

Here's the symbol in question, for context:
![image](https://user-images.githubusercontent.com/92750180/174420427-51a52601-1a21-4f3d-899a-4c150ba8abb2.png)

**Comment by kodabb** [comment]
DMC is also affected

**Comment by andrewgioia** [comment]
Great catch, yes I'll split both up in the next release 👍

**Comment by andrewgioia** [comment]
Added in v3.13.0
