### ISSUE TITLE
[REQUEST] Game Night 2022

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#192]
![image](https://user-images.githubusercontent.com/4212200/180851731-0eb8e3ec-b1c4-4917-9f3a-4f0897822b9a.png)

Set name: Game Night 2022
Set code: GN3

**Comment by csuhta** [comment]
https://c2.scryfall.com/file/scryfall-symbols/sets/gn3.svg

**Comment by andrewgioia** [comment]
Added in v3.12.0
