### ISSUE TITLE
[REQUEST] Alchemy Horizons: Baldur's Gate

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#193]
![alch](https://user-images.githubusercontent.com/4212200/180854124-9b2e146c-bcc4-427b-a2d6-66058706473b.PNG)
_Sorry for the low quality_ :(

Set name: Alchemy Horizons: Baldur's Gate
Set code: HBG

**Comment by Razviar** [comment]
Here's svg from scryfall

<svg class="set-header-symbol" focusable="false" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 49"><g fill="#000" fill-rule="nonzero"><path d="M23.854 4.421c10.815 0 19.583 8.954 19.583 20s-8.768 20-19.583 20c-10.816 0-19.584-8.954-19.584-20s8.768-20 19.584-20ZM23.5 5.5 22 12l-7 5-6-1.5 4 4.5v9l-4.5 4.5 6-1.5 7.5 4.5 1.5 6 2-6 7-4.5 6.5 2-4-5v-9l4-5-6 2-7.5-5-2-6.5Zm0 8.5 8.5 5.5V29l-8.5 6-8-5.5v-10l8-5.5Z"></path><path d="M23.854.453C10.868.453.354 11.191.354 24.421s10.514 23.968 23.5 23.968 23.5-10.738 23.5-23.968S36.84.453 23.854.453Zm0 3c11.314 0 20.5 9.38 20.5 20.968 0 11.587-9.186 20.968-20.5 20.968-11.315 0-20.5-9.38-20.5-20.968 0-11.587 9.185-20.968 20.5-20.968Z"></path></g></svg>

**Comment by youssefm** [comment]
Would like to see this added as well 👍

**Comment by andrewgioia** [comment]
Added in v3.12.0
