### ISSUE TITLE
The Brothers' War (BRO) and related sets

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/keyrune#195]
New sets surrounding The Brothers' War release need icons:

* BRO: The Brothers' War
* BRR: The Brothers' War Retro Artifacts
* BOT: Transformers
* BRC: The Brothers' War Commander

**Comment by giniman** [comment]
https://svgs.scryfall.io/sets/bro.svg
https://svgs.scryfall.io/sets/brr.svg
https://svgs.scryfall.io/sets/brc.svg

**Comment by youssefm** [comment]
@andrewgioia are we likely to get these icons before the set comes out in ten days?

**Comment by andrewgioia** [comment]
Really sorry to everyone on the delay here, life has been busier than normal but I fully intend on staying current and continuing to work on the v4 redraw.

These are now all in v3.11.0.
