### ISSUE TITLE
[REQUEST] Jumpstart 2022, Starter Commander Decks, Phyrexia: All Will Be One

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#197]
Set name: Jumpstart 2022
Set code: J22 (Scryfall)

![jumpstart_2022](https://user-images.githubusercontent.com/4212200/202124940-b0faf0d7-8bdd-4d78-984e-116c9949a341.png)

Set name: Starter Commander Decks
Set code: SCD (Scryfall)

![starter_commander_decks](https://user-images.githubusercontent.com/4212200/202125099-0f259d7f-813e-42cf-8991-c59ad7b431fd.png)

Set name: Phyrexia: All Will Be One
Set code: ONE

![phyrexian_all_will_be_one](https://user-images.githubusercontent.com/4212200/202125603-befc6e64-918c-4177-a06c-8ae6897e38d9.png)

All images were taken from the official [WOTC Marketing Materials](https://wpn.wizards.com/en/marketing-materials#tab_0) page.

**Comment by andrewgioia** [comment]
Thanks @4eveRS and sorry these took so long. All should now be in v3.12.0.

**Comment by 4eveRS** [comment]
Hey @andrewgioia, no worries mate and thanks for all your work😄

I just updated to v3.12 and noticed that a few sets are currently missing:

- **Jumpstart 2022** (J22)
- **Starter Commander Decks** (SCD)
- **30th Anniversary Edition** (30A); _This one is kinda tricky since it's not a symbol and is more like a logotype._

**Comment by andrewgioia** [comment]
Thanks @4eveRS these are now all in v3.12.1
