### ISSUE TITLE
Phyrexia: All Will Be One, March of the Machines

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/keyrune#198]
ONE:
http://svgs.scryfall.io/sets/one.svg

ONC:
http://svgs.scryfall.io/sets/onc.svg

MAT:
http://svgs.scryfall.io/sets/mat.svg

**Comment by tylertyssedal** [comment]
@andrewgioia Are you still actively handling adding new sets?

**Comment by paperorplastic** [comment]
> @andrewgioia Are you still actively handling adding new sets?

Is there anything we can do to help? Love this project!

**Comment by andrewgioia** [comment]
Sorry everyone! Yes I am adding new sets and these comments are extremely helpful in kicking my procrastination. I should have this up tonight or tomorrow morning.

**Comment by paperorplastic** [comment]
> Sorry everyone! Yes I am adding new sets and these comments are extremely helpful in kicking my procrastination. I should have this up tonight or tomorrow morning.

All of these set releases certainly make it more difficult to keep up! Thanks for doing what you do with this project - I get a ton of use out of it for my store!

**Comment by MrTeferi** [comment]
> Sorry everyone! Yes I am adding new sets and these comments are extremely helpful in kicking my procrastination. I should have this up tonight or tomorrow morning.

Thank you for all you do, keyrune is a godsend 🥇 Never feel bad about taking a break to relax, you deserve it :)

**Comment by brianchuchua** [comment]
> > Sorry everyone! Yes I am adding new sets and these comments are extremely helpful in kicking my procrastination. I should have this up tonight or tomorrow morning.
> 
> Thank you for all you do, keyrune is a godsend 🥇 Never feel bad about taking a break to relax, you deserve it :)

Seconding this. I run MTG Collection Builder and Keyrune has saved me from having to Photoshop my own set logos based on Scryfall's logos manually.

I've felt the pain as well of the increased release cycle. Let us know if we can do anything to help in any way. :)

**Comment by andrewgioia** [comment]
Thanks @csuhta, @paperorplastic, @MrTeferi, @brianchuchua, @tylertyssedal, and everyone else for your patience and kind words. Your comments and help here really do mean a lot to me and motivated me to get these all done tonight. Extra special thanks to @paperorplastic, totally unexpected and very much appreciated!

Finally all in v3.12.0 ❤️ Hope all of your projects/stores/everything are going great!

**Comment by tylertyssedal** [comment]
Thanks again @andrewgioia for all your work on this project.

I don't want to resurrect a closed thread, but I also don't want to open a new one. If you'd like to see Keyrune's coverage of all the set variations, you can do so here: [https://tradertools.quietspeculation.com/prices/sets](https://tradertools.quietspeculation.com/prices/sets)

This includes all of the different types of sets as well (promo, memorabilia, etc), which can be filtered at the top. 

And I'm not sure if it's a bug or a caching/deploy issue, but ONE is currently showing up as empty. The CSS is present, but it's not matching to anything in the eof file. 

Once again, thank you, and it looks like a lot of us are happy to lend a hand if you ever need.

**Comment by andrewgioia** [comment]
Thanks @tylertyssedal by all means open new issues if there are bugs/etc., it's definitely easier that way.

For this case I do see ONE loading correctly on your site, perhaps it was just a caching issue? Let me know if I'm seeing something wrong though.

<img width="320" alt="Screen Shot 2023-02-04 at 6 52 47 PM" src="https://user-images.githubusercontent.com/221473/216794461-bf363a4a-c59c-41e8-a82c-1cf61ed1d436.png">

Relatedly I do not see 30A, J22, or SCD. I just added these in 3.12.1 if you want to update again.

**Comment by tylertyssedal** [comment]
Will do @andrewgioia . 

We're using the CDN (`<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/keyrune@latest/css/keyrune.css" media="all">`), which appears to be currently resolving as v3.12.0. 

I had someone else in a different region check and they see what you see (ONE showing up). We both checked and are getting v3.12.0 of the css at the jsdelivr URL. 

[https://cdn.jsdelivr.net/npm/keyrune/css/keyrune.css](https://cdn.jsdelivr.net/npm/keyrune/css/keyrune.css), however, shows 3.12.1. 

> Relatedly I do not see 30A, J22, or SCD. I just added these in 3.12.1 if you want to update again.

I assume your also seeing v3.12.0 when going to the keyrune@latest jsdelivr URL? 

Probably makes sense to chalk it up to jsdelivr's edge propagation since you released v3.12.1 4 hours ago on npm. Not quite sure why my font files aren't version synced, though. 

Either way, glad it appears there's nothing needing fixing on your end.

**Comment by paperorplastic** [comment]
> Thanks @csuhta, @paperorplastic, @MrTeferi, @brianchuchua, @tylertyssedal, and everyone else for your patience and kind words. Your comments and help here really do mean a lot to me and motivated me to get these all done tonight. Extra special thanks to @paperorplastic, totally unexpected and very much appreciated!
> 
> Finally all in v3.12.0 ❤️ Hope all of your projects/stores/everything are going great!

Well deserved in my mind without question. It has been extremely helpful at my store, and I am excited to keep using the font!

**Comment by andrewgioia** [comment]
Closing out as these CDN issues all seem to be resolved
