### ISSUE TITLE
Latest Icons don't seem to show up

### ISSUE THREAD

**Issue by tony-box** [andrewgioia/keyrune#199]
I just installed the latest font pack version 3.12.1 inw Windows for "All Users", but none of the new fonts appear to work in my text editors (for example, Word). I'm unsure if there is any debugging I can provide... never debugged fonts before. Let me know if I can help provide any additional info.

**Comment by wahooka2** [comment]
I ran into the same issue with the font file (ttf) not showing "new" icons after install.  The last installed ttf was from May-2022.  Uninstalling the font from Windows and re-installing the newest worked.  If it helps, I noticed that there were actually two "Keyrune" fonts installed on my machine, both of which I removed prior to the re-install.
I think all of these are the same issue: 174, 179, 199.

**Comment by MrTeferi** [comment]
Yes #174 #179 and this issue can be closed. These are just quirks of installing a new font over previous. Usually installing over previous works fine but for whatever reason sometimes windows doesn't wish to do so, I think I've noticed this happen if you have an app currently running which is using the font currently such as windows or code editor displaying the font contextually etc

If you ever run into this issue, just open font settings in Windows and uninstall **all** copies of Keyrune from windows, then install latest fresh. And for good measure, restart Windows as well (probably not necessary but can't hurt)

**Comment by andrewgioia** [comment]
Thanks all and @MrTeferi for handling, closing out
