### ISSUE TITLE
Magic Online Deck Series

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#20]
I can't confirm this since I don't have access to the cards on MTGO, but as far as I can tell, the Boltslinger and Exiler decks from the [Magic Online Deck Series](http://mtgsalvation.gamepedia.com/Magic_Online_Deck_Series) use this set symbol:

![graphic_seticon_td0_common](https://cloud.githubusercontent.com/assets/641386/22623531/477ca9ae-eb56-11e6-9e36-3e12707658a7.png)

**Comment by fenhl** [comment]
The set code appears to be `TD0`.

**Comment by andrewgioia** [comment]
Added with latest commit
