### ISSUE TITLE
Y22 has the wrong symbol on cheatsheet?

### ISSUE THREAD

**Issue by MrTeferi** [andrewgioia/keyrune#200]
Y22 on the cheatsheet is displaying Kamigawa's set symbol instead of the appropriate alchemy symbol, what displays now:
![image](https://user-images.githubusercontent.com/92750180/221521918-2b5b3d34-4f6e-4728-9bf1-3dc978551a1a.png)

What should be displayed:
![image](https://user-images.githubusercontent.com/92750180/221522136-3d6b1f20-2adc-4e6c-9baa-81a69ef7490a.png)

Just wanted to bring that to attention :)

**Comment by andrewgioia** [comment]
This was a typo, thanks for the catch!

**Comment by andrewgioia** [comment]
Fixed in v3.12.2!
