### ISSUE TITLE
Font Embeddability Setting Prohibits Embedding Font in Documents

### ISSUE THREAD

**Issue by MarkMYoung** [andrewgioia/keyrune#201]
Please add the `Editable` setting the `Font embeddability` setting.

The font cannot be embedded in documents (e.g., Excel spreadsheets) because the `Font embeddability` setting appears to be `Installable`, but does not include `Editable`.  This means that documents using the font which are shared with others or accessed online (e.g., Google Drive) must be accompanied by a font file and subsequently installed.

**Comment by andrewgioia** [comment]
Thanks @MarkMYoung I wasn't aware of this font attribute. I'll take a look to see if the tool I use to create the font supports this or if it's something I need to add after the fact.

**Comment by andrewgioia** [comment]
@MarkMYoung I have an update to the keyrune.ttf file using [ttfpatch](https://github.com/rmuch/ttfpatch) that I pushed up in the latest v3.14.1. Would you be able to test that to see if you can embed the font?

**Comment by andrewgioia** [comment]
Closing this issue for now as I believe embedding is allowed by default when exporting from Icomoon. I inspected the latest version of keyrune.ttf and all embedding was turned on. If this becomes an issue again though I can investigate further.
