### ISSUE TITLE
[Request] Shadows over Innistrad, Commander Masters and Multiverse Legends

### ISSUE THREAD

**Issue by 4eveRS** [andrewgioia/keyrune#202]
Shadows over Innistrad (SIR)
https://svgs.scryfall.io/sets/sir.svg?1678680000

Commander Masters (CMM)
https://svgs.scryfall.io/sets/cmm.svg?1677474000

Multiverse Legends (MUL)
https://svgs.scryfall.io/sets/mul.svg?1677474000

**Comment by RivalRowan** [comment]
The Shadows of the Past bonus sheet that comes with Shadows over Innistrad Remastered also has a set symbol:
https://svgs.scryfall.io/sets/sis.svg

I don't think the Scryfall .SVG is a great version though so I've attached the Arena .png versions as a comparison.
![SIS_Common](https://user-images.githubusercontent.com/128204978/232194039-64505d81-499d-40c8-b825-99c849687e0f.png) ![SIS_Uncommon](https://user-images.githubusercontent.com/128204978/232194040-1b32c49e-9e45-49a5-af74-fac5b80aed47.png) ![SIS_Rare](https://user-images.githubusercontent.com/128204978/232194042-0e01e1e9-415a-4bf8-aada-3811fc69b38d.png) ![SIS_Mythic](https://user-images.githubusercontent.com/128204978/232194043-151c1116-1306-4581-a56f-90530f8a654a.png)

**Comment by andrewgioia** [comment]
Thanks so much for the help @4eveRS and @RivalRowan 👍

**Comment by andrewgioia** [comment]
Added in v3.12.2!
