### ISSUE TITLE
[Request] Lord of the Rings, Explorer Anthology

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#203]
The Lord of the Rings: Tales of Middle-Earth main set:
https://svgs.scryfall.io/sets/ltr.svg

The Lord of the Rings: Tales of Middle-Earth Commander decks:
https://svgs.scryfall.io/sets/ltc.svg

Explorer Anthology (MTG Arena):
https://mtg.fandom.com/wiki/File:EA1_expansion_symbol.png

(sorry, there doesn't seem to be an .SVG on Scryfall for the EA series.)

**Comment by andrewgioia** [comment]
Added in v3.12.2!
