### ISSUE TITLE
Set name should be "March of the Machine", singular

### ISSUE THREAD

**Issue by rickkunkel** [andrewgioia/keyrune#204]
Pedantic issue, sorry :)  The set name -- however odd it sounds -- is apparently "March of the Machine", not "Machines".  Ditto for Commander set.  Reference: [https://magic.wizards.com/en/products/march-of-the-machine](https://magic.wizards.com/en/products/march-of-the-machine)

**Comment by andrewgioia** [comment]
Fixed in v3.12.2!
