### ISSUE TITLE
[Request] Wilds of Eldraine Enchanting Tales

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#208]
Hi Andrew,
Looks like Wilds of Eldraine has a [bonus sheet](https://magic.wizards.com/en/news/announcements/a-first-look-at-wilds-of-eldraine) with its own set symbol - Enchanting Tales.
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/eab3b36a-0b4f-4dda-8700-d124f375fcd2" width="125"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/ca6ad4f8-4568-4740-8f84-af88db999771" width="125"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/02e7fbfc-b0ad-4b27-9a68-29dcb4f9a239" width="125"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/9637967e-f5a0-4d6d-b2f6-c642c055813d" width="125">

Set code = WOT
Contents = 63 enchantments
Scryfall .SVG = https://svgs.scryfall.io/sets/wot.svg

![wot-31-necropotence](https://github.com/andrewgioia/keyrune/assets/128204978/9e409d8c-e3cb-4d79-8a62-84e9e5abed0b)

**Comment by andrewgioia** [comment]
Added in v3.12.3
