### ISSUE TITLE
[Request] Alchemy 2024 (Alchemy: Wilds of Eldraine)

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#209]
Hi Andrew,
We've now got confirmation of at least one Alchemy set in the new 2024 series - Alchemy: Wilds of Eldraine.
The Alchemy sets all follow the same pattern of having one set code for the whole year (~3-4 releases). The 2024 set symbol will be the "A24" seen in the below image.

Arena set code = Y24

Why is the set code and set symbol different? No idea, WotC has never explained that. I assume it's "Alchemy 2024" for the set symbol and "Year 2024" for the set code, but that's purely speculation (and also irrelevant).
I'll update this issue when I get better versions of the set symbol.
![Arena 2023-24 Rotation](https://github.com/andrewgioia/keyrune/assets/128204978/abdf82a0-a387-4b37-99c9-7d8e0c84892f)

**Comment by csuhta** [comment]
They don't use `A**` for Alchemy set codes because `A25` is already taken by Masters 25

**Comment by RivalRowan** [comment]
Oh, that makes a ton of sense. And they couldn't use M25 for Masters 25 because the Core Sets were using M** as their numbering system.

**Comment by andrewgioia** [comment]
Added in v3.12.3
