### ISSUE TITLE
Magic Duels

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#21]
Some cards in Magic Duels (I think the base collection that you get with a new account) use a set symbol similar to the one for M10–M15, but showing a stylized capital D in the bezel. [Here's a screenshot I found](http://gamingtrend.com/wp-content/uploads/2015/07/5-Card-Focus-Deck-Builder.png) showing some cards with this set symbol.

**Comment by andrewgioia** [comment]
@fenhl thanks again for logging all of these, everything except for the unreleased Duel Deck and the MTGO treasure chest symbol are added. I need to wait for a higher res source image of the DD and I'm going to work on that treasure chest either today or tomorrow.
