### ISSUE TITLE
[Alt Symbol] Battle Royale Box Set

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#213]
Hi Andrew,
I was poking through the MTG product archive and noticed that the Battle Royale Box Set (BRB) uses a different set symbol from the one in Keyrune and Scryfall. At the moment, BRB is using a battle axe but all the Wizards of the Coast sources I've checked use a stylized "BR".

I'm not sure where the battle axe version came from. I've queried Scryfall and they've just said it was inherited from Magiccards.info.
The actual cards in the decks never used a unique set symbol, they only had their original printing symbol, so it's a bit arbitrary what is used.

![BRB_C](https://github.com/andrewgioia/keyrune/assets/128204978/24005404-b9af-4dbb-a1e6-f69c312b9760) ![BRB_U](https://github.com/andrewgioia/keyrune/assets/128204978/d57f684e-c643-4e57-86e1-85a173d274ab) ![BRB_R](https://github.com/andrewgioia/keyrune/assets/128204978/9d301a4e-8de4-4801-a4ae-85822e1358f6)

For comparison, the Scryfall .SVG (the battle axe version): https://svgs.scryfall.io/sets/brb.svg

**Official Sources**
Gatherer: https://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&name=+[A]&set=+[%22Battle%20Royale%20Box%20Set%22]

MTG Product Archive:
![Battle_Royale_Product_archive](https://github.com/andrewgioia/keyrune/assets/128204978/5ed8b191-b95d-4b32-baff-09d6aa50e2f1)

Magic Online set filter:
![MTGO_brb](https://github.com/andrewgioia/keyrune/assets/128204978/ebd89d6e-4095-4f10-8b94-353b389122da)

**Comment by andrewgioia** [comment]
Added in v3.12.3
