### ISSUE TITLE
[Alt Symbol] Unfinity - Acorn cards

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#214]
Hi Andrew,
The other thing to come out of poking around in the Product Archive is that WotC has introduced a second set symbol for Unfinity.
Cards that are eternal-legal retain the atom symbol that's already been released. Acorn cards are getting a new set symbol on Gatherer. This symbol, presumably, is only going on Gatherer unless they reprint any Unfinity cards.

![UNA_C](https://github.com/andrewgioia/keyrune/assets/128204978/1d57a320-9789-444c-8fe3-194d778590ce) ![UNA_U](https://github.com/andrewgioia/keyrune/assets/128204978/843c19ce-1642-4755-8f41-71306b8d8023) ![UNA_R](https://github.com/andrewgioia/keyrune/assets/128204978/84ac455e-950c-416d-b877-784d055c1066) ![UNA_M](https://github.com/andrewgioia/keyrune/assets/128204978/f5887452-e543-4bac-b0af-8eda34cb1e45)

Set Code = UNA (from the image file names on Gatherer)
Gatherer: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=580760
Product Archive:
![Unfinity_Product_archive](https://github.com/andrewgioia/keyrune/assets/128204978/cab4d06a-ec33-4683-a65d-442c7795a937)

**Comment by andrewgioia** [comment]
Added in v3.12.3
