### ISSUE TITLE
[Request] Universes Beyond: Fallout

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#218]
Hi @andrewgioia,
WotC have [previewed](https://www.youtube.com/watch?v=nYla3gjHUHA) the [first look](https://magic.wizards.com/en/news/announcements/a-first-look-at-magic-the-gathering-fallout-available-march-2024) at Universes Beyond: Fallout. The product will be four Commander decks.

This set is the same release style as the Doctor Who decks.

Set code = PIP
Scryfall .SVG = 
Official product page = https://magic.wizards.com/en/products/fallout

<img src="https://github.com/andrewgioia/keyrune/assets/128204978/be743ba9-a50e-4cd9-8f71-0d1a06c9623c" width="150"/> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/01d2c0ac-d1be-4d1b-bca5-ea7727b403c5" width="150"/> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/81f63795-ef20-459d-8f23-d50a538e97f4" width="150"/> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/24891f3d-d133-4527-87b0-dda9f952126a" width="150"/>

![pip-340-dogmeat-ever-loyal](https://github.com/andrewgioia/keyrune/assets/128204978/ffa9da08-d637-4718-a3c3-18277a308862)

**Comment by csuhta** [comment]
Scryfall symbol: http://svgs.scryfall.io/sets/pip.svg

**Comment by andrewgioia** [comment]
Added in v3.13.0
