### ISSUE TITLE
[Request] Murders at Karlov Manor & Ravnica: Clue Edition

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#223]
Hi Andrew,
The [First Look](https://magic.wizards.com/en/news/announcements/a-first-look-at-murders-at-karlov-manor) at Murders at Karlov Manor (MKM) and Ravnica: Clue Edition (CLU) has been released and the new set symbols revealed. MKM is the standard premier set, so nothing unusual there. CLU is... well I'm still not sure what it is exactly, but it's release is similar to the Theros block [challenge decks](https://mtg.fandom.com/wiki/Challenge_Deck).

**Murders at Karlov Manor** (Main set)
Set Code: MKM
Scryfall .SVG: https://svgs.scryfall.io/sets/mkm.svg
Official Product Page: https://magic.wizards.com/en/products/murders-at-karlov-manor
WPN Product Page: https://wpn.wizards.com/en/products/murders-at-karlov-manor

<img src="https://github.com/andrewgioia/keyrune/assets/128204978/1918c0f4-5bb9-4e59-85d6-6d1834915f73" width="150"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/6adc32bb-a4b3-407d-9078-f308d2217aa2" width="150"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/e724efc1-c2c6-41fe-b337-0971f96a57d2" width="150"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/56193ede-74be-4dbd-ab65-6de7356d799d" width="150">

**Murders at Karlov Manor Commander**
Set Code: MKC
Scryfall .SVG: https://svgs.scryfall.io/sets/mkc.svg

<img src="https://github.com/andrewgioia/keyrune/assets/128204978/20de6653-6e67-4b46-8097-ec91b96cd733" width="150"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/44988bca-7228-4c1d-acf6-76a7687a5d1d" width="150"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/7498f7ba-608c-4965-8e37-59140313930c" width="150"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/c2077eb0-7a10-458a-8144-43eabfcaa62c" width="150">

**Ravnica: Clue Edition**
In some locations, the game "Clue" is known as "Cluedo". In those markets, the set will be known as _Ravnica: Cluedo Edition_.

Set Code: CLU
Scryfall .SVG: https://svgs.scryfall.io/sets/clu.svg
Official Product Page: https://magic.wizards.com/en/products/murders-at-karlov-manor
WPN Product Page: _TBA_

<img src="https://github.com/andrewgioia/keyrune/assets/128204978/d08fa2bc-e814-4a62-b92d-cfa0645630de" width="150"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/6b0cec32-6f8f-4e66-87a4-55a931e79006" width="150"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/04b4a571-725c-4696-9bdc-7077db32a99c" width="150"> <img src="https://github.com/andrewgioia/keyrune/assets/128204978/e4b5f568-183f-45fb-84c0-d55552604dd7" width="150">

**Comment by csuhta** [comment]
Here's our renders:
https://svgs.scryfall.io/sets/mkm.svg
https://svgs.scryfall.io/sets/mkc.svg
https://svgs.scryfall.io/sets/clu.svg

**Comment by andrewgioia** [comment]
All are now in v3.14.0, sorry everyone for the super late update for these!
