### ISSUE TITLE
[Request] Outlaws of Thunder Junction, Bloomburrow, Assassin's Creed, Modern Horizons III

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#225]
Hi @andrewgioia,
WotC had their [Preview Panel](https://www.youtube.com/watch?v=CzU5u3WUlM8) at MagicCon: Chicago today and went through four of the news sets for 2024. They've also put a series of First Look articles up on the Mothership. This is just a roundup of the various set symbols they've released.

### Outlaws of Thunder Junction
First look: [https://magic.wizards.com/en/news/announcements/a-first-look-at-outlaws-of-thunder-junction](https://magic.wizards.com/en/news/announcements/a-first-look-at-outlaws-of-thunder-junction)
**Main set**
Set code: OTJ
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/2601f4c0-dc78-4afc-aed1-06fe3d9fe81f" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/3ab44e73-ba6e-4066-bcc4-b036a34593fc" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/daf1b671-ae88-4d77-882f-58cbc6e62525" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/bc414c3d-dbcc-454d-b9c0-ceaafeb0555d" width="150">

**Commander decks**
Set code: OTC
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/b378ddfb-af40-4aff-9e8e-8f94ecc0bbae" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/50cb8d70-b6e2-499d-9f40-4d149a0afdda" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/f5f9d0e6-8440-4804-b586-cab948e7bfa2" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/c16b3728-c88f-4848-8e85-0bbecff3f922" width="150">

**Breaking News**
This is the set's [bonus sheet](https://mtg.fandom.com/wiki/Bonus_sheet) that reprint "crimes", Crime is a new keyword for the set; players commit crimes by casting any spell or activating any ability that targets an opponent, their hand, library and/or graveyard, or one or more permanents they control.
Set code: OTP
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/28eda640-bb39-42e8-8dbb-c8230ad98722" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/40778adc-34a8-45af-94c9-481532eb5574" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/8e5dd244-ad55-4816-9d30-73b82640c630" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/7bfae4e7-f5c8-4218-b27e-70534cadbf7d" width="150">

**The Big Score**
Set code: BIG
For Outlaws of Thunder Junction, the regular slots in Play/Collector boosters taken by [The List](https://mtg.fandom.com/wiki/The_List) cards are being replaced with a special set of reprints called The Big Score. These get their own set code and symbol. They are essentially special guest [Special Guests](https://mtg.fandom.com/wiki/Special_Guests).
_Note: This set of cards was originally its own Epilogue set - similar to March of the Machine: The Aftermath. When that set failed, they cancelled The Big Score and put most of the cards into the regular OTJ booster. They're all Standard legal cards as a result._
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/a1fdea37-e61f-4b6f-8178-8937ef45c440" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/2fb1b9c4-52c8-4738-b91c-477b3f7893a6" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/1cdc00e1-fa49-4f30-b112-a389e7ec6dce" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/592d44b2-b8e2-4ab1-bb42-001a9ee705f9" width="150">

### Bloomburrow
First look: [https://magic.wizards.com/en/news/announcements/a-first-look-at-bloomburrow](https://magic.wizards.com/en/news/announcements/a-first-look-at-bloomburrow)
**Main set**
Set code: BLB
_Note for those using light mode_ The stem of the holly/oak/maple leaf in the common set symbol is white, which doesn't show up well against GitHub's white background.
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/b387f83f-24b7-4cc0-970a-6a4e92c3826c" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/7dd8e643-d98b-45b1-803b-66a1350ce2e4" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/2847aa04-9598-41e8-bc8e-80aa41097e89" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/ba2ae7bd-e70c-4acb-b4c8-862e90da58f8" width="150">

**Commander decks**
Set code: BLC
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/61d418d1-bb95-44df-b94e-143b11fb53db" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/9d7a909c-69b8-4348-b679-450ca4317ca7" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/6591bc22-9aeb-470e-b983-aa8532cf0f5f" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/e5f6c3a5-3620-450a-b566-4bf5e6016e66" width="150">

### Universes Beyond: Assassin's Creed
First look: [https://magic.wizards.com/en/news/announcements/a-first-look-at-magic-the-gathering-assassins-creed](https://magic.wizards.com/en/news/announcements/a-first-look-at-magic-the-gathering-assassins-creed)
Set code: ACR
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/1a10d4fd-2c6c-4bad-93ab-f0716fb5a460" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/5cd637ba-1e20-4f5d-91ad-b3b488e14070" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/b3908c7b-14ed-44f4-883c-e40c7719ef78" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/6e4b63d3-05db-49a8-a049-887c5315793c" width="150">

### Modern Horizons III
First look: [https://magic.wizards.com/en/news/announcements/a-first-look-at-modern-horizons-3](https://magic.wizards.com/en/news/announcements/a-first-look-at-modern-horizons-3)
**Main set**
Set code: MH3
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/d851fc34-6199-407a-9232-3cf98c769fc2" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/4ed87331-e92e-4680-8f58-eafef1f0c744" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/b1a36398-78e1-4698-ad47-99cc339687f3" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/9ede2303-2ed7-4ff7-9c12-aaf129825e15" width="150">

**Commander decks**
Set code: M3C
_Note:_ After some initial confusion, it's now been made clear that the set code for the Commander decks is, in fact, M3C.
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/067ce952-5a8e-4b85-9ae3-d2767be6c3b4" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/9988687b-f487-4f3a-abc2-2c9fad1c4f93" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/26e6b86d-da8f-4eae-a095-9eada83aefe1" width="150"><img src="https://github.com/andrewgioia/keyrune/assets/128204978/346f2133-bedd-4f4e-b7c6-c3f89876e4e5" width="150">

**Comment by andrewgioia** [comment]
Thanks @RivalRowan! I have quite a bit of work this weekend 😜

I plan to get these and the other missing ones all added by Sunday, sorry for the delays again.

**Comment by andrewgioia** [comment]
Icons are all traced and added, just need to organize and update docs before pushing tomorrow morning

**Comment by andrewgioia** [comment]
SVGs for anyone interested now, otherwise they'll be in the `SVG` director for v3.14.0:

![M3C  Modern Horizons 3 Commander (inner)](https://github.com/andrewgioia/keyrune/assets/221473/ce40c5ee-eee9-4850-ac9b-8e05ddad07f5)
![M3C  Modern Horizons 3 Commander (rarity)](https://github.com/andrewgioia/keyrune/assets/221473/cb51733c-d8e0-46a4-9430-a3407323d646)
![MH3  Modern Horizons 3](https://github.com/andrewgioia/keyrune/assets/221473/61d41e5d-b704-4afd-b740-6166840034f9)
![ACR  UB Assassin's Creed](https://github.com/andrewgioia/keyrune/assets/221473/d9e607a6-46c4-4c98-aa95-8db7206b53a8)
![BLC  Bloomburrow Commander](https://github.com/andrewgioia/keyrune/assets/221473/96cddc95-73a4-4664-8374-b6246dc51bbf)
![BLB  Bloomburrow](https://github.com/andrewgioia/keyrune/assets/221473/5dc57351-afe8-458f-b833-aa89cf7f6ce4)
![BIG  The Big Score](https://github.com/andrewgioia/keyrune/assets/221473/f23a3382-e81b-4591-80e8-b62c8959d553)
![OTP  Breaking News](https://github.com/andrewgioia/keyrune/assets/221473/6883439a-f448-466a-b41b-465a3cd793da)
![OTJ  Outlaws of Thunder Junction Commander (inner)](https://github.com/andrewgioia/keyrune/assets/221473/c5e99d31-1fbf-4c08-9cd8-d75056b44629)
![OTJ  Outlaws of Thunder Junction Commander (rarity)](https://github.com/andrewgioia/keyrune/assets/221473/373c1242-673b-406a-8299-748b7c435063)
![OTJ  Outlaws of Thunder Junction](https://github.com/andrewgioia/keyrune/assets/221473/25b62afc-f435-4211-b05e-4c53d1f96e51)

**Comment by andrewgioia** [comment]
All in v3.14.0 👍

**Comment by Emnalyeriar** [comment]
@andrewgioia In the latest version from jsdelivr it seems that the Bloomburrow (blb) set icon is being displayed as Bloomburrow Commander (blc) icon (.ss-blb shows the commander blc commander icon)
