### ISSUE TITLE
[Documentation] The Big Score (BIG) under 

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#227]
Hi @andrewgioia,
Sorry, just noticed a minor issues on the [documentation page](https://keyrune.andrewgioia.com/icons.html).

The unicode in the documentation is listed as "e9c8" but it should be "e9d6".

The Big Score (BIG) has been documented under _Reprint Sets_. It's not a reprint set, all the cards are brand new designs and are Standard-legal. It should be listed under _Expansion Sets_, after Outlaws of Thunder Junction (OTJ).

Originally it was a stand-alone epilogue set, like March of the Machine: The Aftermath (MAT), but when MAT bombed, WotC cancelled the separate release. They still had all the card designs and decided to put them into OTJ play boosters instead of The List cards. They kept the cards as Standard-legal though. So technically we're getting two sets worth of cards in one play booster with OTJ.

**Comment by andrewgioia** [comment]
Fixed!
