### ISSUE TITLE
Rendering issues on icons (half bold)

### ISSUE THREAD

**Issue by kalinon** [andrewgioia/keyrune#229]
Seeing a weird issue where for some sets half the icon is bold. I am using the `latest` from the `cdn.jsdelivr` link which seems to be resolving to `3.13.1`. If i have time i will test it against `1.14.0`. This issue doesnt seem to effect "foil" versions of the symbols. See screen shots for details. Noticed it on the following sets: `ONE`, `DMU`, `C16`, `BRO`

![Screenshot 2024-03-11 at 11 03 42 AM](https://github.com/andrewgioia/keyrune/assets/5629164/ac4dfc12-5211-4e50-93a8-c76ad0e4d76d)
![Screenshot 2024-03-11 at 11 04 35 AM](https://github.com/andrewgioia/keyrune/assets/5629164/2352a853-36e1-46cf-8fcc-1fdb13cf8d9e)

**Comment by andrewgioia** [comment]
Wow very strange! @kalinon do you still see this issue? Sorry for the late reply here, I can't replicate it but if you are still getting it could you let me know?

**Comment by andrewgioia** [comment]
<img width="922" alt="Screenshot 2024-10-28 at 12 04 27" src="https://github.com/user-attachments/assets/fd8d2d81-572d-4b16-822a-314357559196">
