### ISSUE TITLE
Duel Decks: Mirrodin Pure vs. New Phyrexia

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#23]
*Duel Decks: Mirrodin Pure vs. New Phyrexia* is a Duel Decks set specific to Magic Online.

![graphic_seticon_td2_common](https://cloud.githubusercontent.com/assets/641386/22623658/379bd394-eb5a-11e6-9b80-fcaa287d2023.png)

The set code appears to be `TD2`.

**Comment by andrewgioia** [comment]
Added with latest commit
