### ISSUE TITLE
[Request] Alchemy 2025

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#231]
Hi @andrewgioia,
It looks like the Alchemy 2025 set symbol has been made public. It's the same as each previous year, just with a "25" now.

Arena set code = Y25
![Y25_Common](https://github.com/andrewgioia/keyrune/assets/128204978/63efe4b0-50a6-49a6-ba28-be9ab3c073a2) ![ExpansionSymbol_Y25_Uncommon](https://github.com/user-attachments/assets/44dbb442-05de-4b11-a25c-1beb87fc0605) ![ExpansionSymbol_Y25_Rare](https://github.com/user-attachments/assets/e5afc03c-57e2-4d56-9064-b8f9a3379181) ![ExpansionSymbol_Y25_Mythic](https://github.com/user-attachments/assets/3c5cca00-9377-4972-ae5c-af3e2f1d0aa2)

**Comment by scarletcs** [comment]
This symbol is used by Alchemy: Bloomburrow.
https://scryfall.com/sets/yblb

**Comment by andrewgioia** [comment]
Thanks all, adding this and mapping for incoming release

**Comment by andrewgioia** [comment]
Added in v3.15.1 👍
