### ISSUE TITLE
[Request] Duskmourn: House of Horror

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#232]
Hi @andrewgioia,
The Japanese [_Magic: The Gathering_ page](https://mtg-jp.com/reading/publicity/0037926/) has spoiled two Japanese promos for Duskmourn: House of Horror. The new set symbol is a butterfly/moth.

**Main Set**
Set code = DSK
Scryfall .SVG = http://svgs.scryfall.io/sets/dsk.svg
Official product page = https://magic.wizards.com/en/products/duskmourn-house-of-horror
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/9c283bfc-a710-470a-a9f5-e6d85221605b" width=150><img src="https://github.com/andrewgioia/keyrune/assets/128204978/e6548a05-84e2-4ebb-ab77-b5c56ed6b777" width=150><img src="https://github.com/andrewgioia/keyrune/assets/128204978/49ed393c-2bbd-4a71-9673-0ae9bd972c5b" width=150><img src="https://github.com/andrewgioia/keyrune/assets/128204978/02ae803f-55db-404e-a0f7-3fa1e05a82c4" width=150>

<img src="https://github.com/andrewgioia/keyrune/assets/128204978/1bf54959-0da0-449c-bc97-eaff8b7cd90e" width=500>

**Duskmourn: House of Horror Commander decks**
Set code = DSC
Scryfall .SVG = https://svgs.scryfall.io/sets/dsc.svg
<img src="https://github.com/andrewgioia/keyrune/assets/128204978/3bc41e5e-5b6e-4050-8ecb-b1aa57af691e" width=150><img src="https://github.com/andrewgioia/keyrune/assets/128204978/28cfef43-a4cc-47b4-854f-3f786373a1a8" width=150><img src="https://github.com/andrewgioia/keyrune/assets/128204978/9b1ef7a8-a22e-4f94-b5ff-026fcaf73ac2" width=150><img src="https://github.com/andrewgioia/keyrune/assets/128204978/be0e823a-96ba-4d11-84d6-39280aa2afe6" width=150>

**Comment by csuhta** [comment]
Here's our draw: http://svgs.scryfall.io/sets/dsk.svg

**Comment by Horsty80** [comment]
I'm work on it 
I've fork the repo and try to understand how it's work to generate the font

Today I've success generate the font for it 

I need to update the keyrune font file or recreate manually :'( 
I don't know how to update the font file for the moment


<img width="200" alt="Capture d’écran 2024-08-11 à 16 19 22" src="https://github.com/user-attachments/assets/08372e69-06c0-4f64-952b-aca734880eb5">

**Comment by Horsty80** [comment]
@RivalRowan I've open PR for this 

If you need it, I have fork the repo, and create a release with DSK set here https://github.com/Horsty80/keyrune/releases/tag/v3.15.0

**Comment by andrewgioia** [comment]
Hi guys, apologies for by absence here, been dealing with some unfortunate personal issues for quite a bit.

I plan to add these this week and get everything up to date again. Again apologies for those who rely on this and for not having it current when these are announced.

**Comment by Horsty80** [comment]
> Hi guys, apologies for by absence here, been dealing with some unfortunate personal issues for quite a bit.
> 
> I plan to add these this week and get everything up to date again. Again apologies for those who rely on this and for not having it current when these are announced.

Hey :) happy come back Andrew ✌️
I hope everything is okay for you and don't apologies, you have a life outside this repo :p 

I have skill up on how to contribute, I open a unique PR (close other) with some fix and improvement.
Let me know if I'm right on thing I say inside it x) 

Thanks ✌️

**Comment by Horsty80** [comment]
Can be close @andrewgioia ✌️

**Comment by skoruppa** [comment]
@Horsty80 I think the commander is still missing

**Comment by Horsty80** [comment]
> @Horsty80 I think the commander is still missing

You are right ! I will add it soon
Thanks ✌️

**Comment by andrewgioia** [comment]
This has been added
