### ISSUE TITLE
[Request] Magic: The Gathering Foundations

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#233]
Hi @andrewgioia,
The [Preview Panel](https://www.youtube.com/watch?v=Is_ghoPFjrw) at MagicCon Amsterdam has been and gone and brought with it a new product line - _Magic: The Gathering Foundations_. This set is a cross between a Portal/Starter set, a Core set, and the Arena Base Set. It's designed to essentially be an evergreen Standard-legal set but WotC have stated it wont rotate out until 2029 at the earliest in case something goes wrong. It contains new card designs, reprints and it includes Planeswalker cards.

Set code = FDN
Scryfall .SVG = https://svgs.scryfall.io/sets/fdn.svg
Official product page = https://magic.wizards.com/en/products/foundations
Announcement = https://magic.wizards.com/en/news/announcements/announcing-magic-the-gathering-foundations

<img src="https://github.com/user-attachments/assets/7e13247a-9109-4e8e-b276-612ac031ceee" width="175"> <img src="https://github.com/user-attachments/assets/0ece43a7-9a87-4f22-9d02-74453f65fd7e" width="175"> <img src="https://github.com/user-attachments/assets/b1a5f9dc-8317-44f5-99bf-a229d68deb83" width="175"> <img src="https://github.com/user-attachments/assets/69c95a6c-00c6-41aa-9035-150a2c9392c2" width="175">

![Llanowar Elves_FDN](https://github.com/andrewgioia/keyrune/assets/128204978/b10699ce-6ee9-40e4-bb5f-132a8d337caf)

**Comment by Horsty80** [comment]
@RivalRowan same for Foundation https://github.com/Horsty80/keyrune/releases/tag/v3.15.0

It's just a try to understand how this repo work, so only the "dark icon" is update.
If you want to try and let me some feedback to improve it ✌️

**Comment by Horsty80** [comment]
Can be close @andrewgioia ✌️

**Comment by RivalRowan** [comment]
Hey @andrewgioia, I do have to apologize.
In the craziness yesterday I missed a detail in the [Collecting Foundations](https://magic.wizards.com/en/news/feature/collecting-foundations) article. As a product line, _Magic: The Gathering Foundations_ doesn't have any Commander decks but it does have Commander _cards_ (only legal in Vintage, Legacy and Commander). These cards have their own set symbol and set code.

**Foundations Commander**
Set code = FDC
Scryfall .SVG = TBA
Announcement = https://magic.wizards.com/en/news/feature/collecting-foundations
![FDC_symbol](https://github.com/user-attachments/assets/7c130214-69e4-408b-942a-c1f600202c72)

**Comment by andrewgioia** [comment]
Oops, keeping this open as I did not see that there is a FDC! Will get that into v3.16.0 with the new expansion
