### ISSUE TITLE
Bug report: BLB is incorrectly displayed as BLC

### ISSUE THREAD

**Issue by HeliumOctahelide** [andrewgioia/keyrune#234]
In `keyrune.css`, `.ss-blc` was mistakenly entered as `.ss-blb`. This causes `.ss-blb` to be incorrectly rendered as the BLC icon.
![image](https://github.com/user-attachments/assets/43d9d0c5-5ff6-4962-9069-693ae3ff9f65)

**Comment by HeliumOctahelide** [comment]
I just created a pull request to fix this.

**Comment by nikkitousen** [comment]
This has been broken for a while now, any chance we can bump this issue so that @HeliumOctahelide 's  PR is approved/merged quickly? @andrewgioia

**Comment by Horsty80** [comment]
No commit on the repo since 5 months =/

I hope @andrewgioia come back to us 

Their are other mainteners of this repos ?

**Comment by andrewgioia** [comment]
Sorry @HeliumOctahelide, @Horsty80, and all--I should have these issues addressed this week and will merge the PRs asap.

Apologies for letting this go for so long.

**Comment by Horsty80** [comment]
Can be close @andrewgioia ✌️

**Comment by Horsty80** [comment]
@HeliumOctahelide can you close your issue please :) ? 

It's resolve now

Thanks
