### ISSUE TITLE
[Request] Foundations Jumpstart

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#236]
Hi @andrewgioia,
Alongside the announcement of _Magic: The Gathering Foundations_  (#233), WotC are releasing a new jumpstart set for 2025 - _Foundations Jumpstart_. This is part of the product lineup for Magic: The Gathering Foundations but has a slightly different brand name ("Foundations", as opposed to "Magic: The Gathering Foundations") and totally separate set symbol. All the other rules of a jumpstart product apply though (20 card half-deck boosters, 46 different themes, etc.)

Set code = J25
Scryfall .SVG = TBA
Announcement = https://magic.wizards.com/en/news/announcements/announcing-magic-the-gathering-foundations

![J25_expansion_symbol](https://github.com/user-attachments/assets/add17495-fa4e-4d30-a744-563ea2ec90ee) (Yes, the set symbol looks weirdly cut off. It's not an error in the image, that's just how it looks.)

<img src="https://github.com/user-attachments/assets/adf33d4b-55d3-4c75-9f87-8043f96b9458" width="400">

**Comment by Horsty80** [comment]
@RivalRowan I didn't find the svg it's not available on scryfall
If you have it can you share it ? thanks

**Comment by RivalRowan** [comment]
@Horsty80, thanks for all your efforts with this project!
Scryfall won't have an .SVG available for a set until at least one card from the set has been previewed. This hadn't happened until the preview panel at MagicCon Las Vegas today.

There are a couple of places on the internet that are doing set symbol .SVGs other than Andrew.
I've referenced the Slightly Magic forum [Vector Set Symbols and Watermarks](https://www.slightlymagic.net/forum/viewtopic.php?f=15&t=7010&sid=9b2d44fb39121566a8009d561114c810) thread in the past.

**Comment by RivalRowan** [comment]
Latest news on Foundations _Jumpstart_ (J25) is here:
https://www.thegamer.com/magic-the-gathering-mtg-foundations-jumpstart-visual-spoiler-every-card/#latest-reveals---october-25-2024

**Comment by andrewgioia** [comment]
Added in v3.15.1
