### ISSUE TITLE
[Request] Mystery Booster 2

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#237]
Hi @andrewgioia,
At Gen Con 2024, Gavin [announced](https://twitter.com/GavinVerhey/status/1819452632521756808) that MagicCon Las Vegas would feature the debut of _Mystery Booster 2_. 

The [Mystery Booster](https://mtg.fandom.com/wiki/Mystery_Booster) product is a giant set of reprints from across Magic history with the product twist being the inclusion of some "[playtest cards](https://mtg.fandom.com/wiki/Mystery_Booster/Test_cards)" that can be used in Mystery Booster limited events. Last time it was printed, the set did not have its own set symbol. It used the pick-up printing method of The List, meaning the cards retained their original printing set symbol and instead had a small white planeswalker logo printed in the bottom right-hand corner.

For Mystery Booster 2, the set is getting a unique symbol that is used on the white-bordered, Future Sight frame, and digital exclusive reprint cards (but not the normal black-bordered reprints or test cards).

Set code = MB2
Scryfall .SVG = https://svgs.scryfall.io/sets/mb2.svg
Announcement = https://magic.wizards.com/en/news/announcements/announcing-mystery-booster-2

![MB2_expansion_symbol](https://github.com/user-attachments/assets/1ba25816-819c-458b-b41d-05931c503f40)

**Comment by Horsty80** [comment]
@RivalRowan the mystery booster 2 icon is up to date now :) 

Can you close this issue ? Thanks ✌️

![Capture d’écran 2024-09-30 à 00 44 55](https://github.com/user-attachments/assets/595f201e-a3a0-4903-893c-dbb6df1cce43)

**Comment by andrewgioia** [comment]
This is all set as of v3.15.1
