### ISSUE TITLE
Magic Online Player Rewards

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#24]
Some cards on Magic Online, such as the morph overlay in eternal formats and the [Magic Online Player Rewards](http://magic.wizards.com/en/content/magic-online-player-rewards), use the Magic Online logo as their set symbol.

**Comment by andrewgioia** [comment]
@fenhl excellent finds here, thank you for compiling all of these and submitting issues. I'll take a look later this evening and should be able to knock them out this week.

**Comment by yandere-sliver** [comment]
There seem to be in fact several player reward items in MTGO. The icon mentioned by Fenhl. The legendary cube icon and a treasure chest icon. 

![mtg icon pz2](https://cloud.githubusercontent.com/assets/25598912/22673143/adc0cdde-ecd8-11e6-91c6-12c63d760dc5.png)
![mtg icon prm](https://cloud.githubusercontent.com/assets/25598912/22673145/b224df3c-ecd8-11e6-8a6c-6d6a306ab1ed.png)

PS: We installed your font at https://mtgsalvation.gamepedia.com, so if you need any haelp you know where to find us. :)

**Comment by andrewgioia** [comment]
@yandere-sliver that's awesome! I added the MTGO symbol but haven't been able to find anything on the treasure chest icon (let along a higher res version unfortunately). Where did you get the version you pasted here? 

If you have anything larger that would be a huge help; I can certainly draw this one but I like to get a bit larger versions so I can make sure they're as close as possible.

**Comment by yandere-sliver** [comment]
Got the thing from MTG Goldfish: https://www.mtggoldfish.com/index/PZ2#online

**Comment by yandere-sliver** [comment]
Okay found out a bit more. The chest seem to belong to the "you make the cube" stuff which seems to have the set code PZ2. Legendary Cube would have been the PZ1,

On card horder you can see an actual card with this icon: https://www.cardhoarder.com/cards/62341/pz2-ash-barrens

Do you know if you can rip the icon from the MTGO client?

**Comment by csuhta** [comment]
@andrewgioia I vectorized the chest icon for You Make the Cube (PZ2) prizes, I hope it's helpful:

[You Make the Cube PZ2.svg.zip](https://github.com/andrewgioia/Keyrune/files/798344/You.Make.the.Cube.PZ2.svg.zip)

Here are are two examples of the icon from the MTGO interface:

![1thvvrg1](https://cloud.githubusercontent.com/assets/769083/23290156/b59ca180-fa1c-11e6-9b8d-64ea10be0c9e.png)
![buzqatc4](https://cloud.githubusercontent.com/assets/769083/23290157/b6eaa046-fa1c-11e6-9add-eab809c196a3.png)

**Comment by andrewgioia** [comment]
Thanks so much @yandere-sliver and @csuhta, I looked at the MODO assets but it didn't include the Treasure Chest logo unfortunately. I slightly modified yours, Corey, just to curve the top 4 blocks of the chest's lid every so slightly. It looks fantastic.

Thanks again guys, I just pushed this update.
