### ISSUE TITLE
Incorect unicode values on docs page

### ISSUE THREAD

**Issue by ixty** [andrewgioia/keyrune#243]
Hello,

It appears the wrong value is displayed on the documentation page https://keyrune.andrewgioia.com/icons.html?icon=blb

It says the value is 0xe9cf which is the value for MH3, the correct value is 0xe9cd.

Thanks for the great font btw!

**Comment by Horsty80** [comment]
Hello @ixty 

![Capture d’écran 2024-09-30 à 00 36 52](https://github.com/user-attachments/assets/6c5ac51e-cebc-47c1-a337-2ca6ec9c08ff)

![Capture d’écran 2024-09-30 à 00 38 08](https://github.com/user-attachments/assets/956832a7-256a-47bd-8407-7eaa4aaac0e3)

the unicode for blb is e9cd
the unicode for mh3 is e9cf

Indeed there are a missmatch in icons.html mh3's unicode has been set in blb's unicode too.
I will fix that
