### ISSUE TITLE
C16 Symbol missing sword tip and pommel

### ISSUE THREAD

**Issue by HexOoze** [andrewgioia/keyrune#246]
The actual symbol on the C16 cards looks like this:
![AC16](https://github.com/user-attachments/assets/6db2aba8-2030-41b2-96e4-296560862ada)
(from [scryfall](https://scryfall.com/card/oc16/50/yidris-maelstrom-wielder))
![IAC16](https://github.com/user-attachments/assets/a109239f-ff76-4e46-ae10-42573dc89b60)
It doesn't seem right whether gradient on or not.

**Comment by andrewgioia** [comment]
This is a great catch, it has to do with the "layer" of the set symbol used for the rarity gradient vs the layer used for the border. In this case, the rarity is the inner shield portion and all of the black is the border.

Whenever the new version of Keyrune releases this is properly handled with multiple glyphs, but for now we need to decide which layer gets to be the rarity layer. In this case it came out weird and you're right, the sword _should_ be present in the symbol.

Common symbols sometimes reverse this, like you can see in [Command Tower](https://scryfall.com/card/c16/286/command-tower). The white layer in that symbol is the "rarity" layer and the inside black becomes the border ( which is red here). That white layer makes more sense if we have to pick one and we can definitely replace that in one of the next versions 👍
