### ISSUE TITLE
[Request] Pioneer Masters (MTGA)

### ISSUE THREAD

**Issue by RivalRowan** [andrewgioia/keyrune#249]
Hi @andrewgioia,
More stuff I missed yesterday. Sorry!

_[Pioneer Masters](https://mtg.fandom.com/wiki/Pioneer_Masters)_ has been officially announced as coming to _Magic: The Gathering Arena_ on December 10th, 2024. There's no official article on this yet (just a [couple](https://twitter.com/wizards_magic/status/1849916401437605930) of [tweets](https://twitter.com/wizards_magic/status/1849916731034304589)), so I don't know what the set code will be. There were two preview cards though.

The set is exclusive to Arena and is intended to bring all the missing tournament staples from the tabletop Pioneer format to the client. On top of that, it's also supposed to be a draftable set. It should be 100% reprints with no new cards.

![PMR_Hidden Strings](https://github.com/user-attachments/assets/6fa5a661-1194-4597-ac79-5f2dd1fe7344)
![PMR_Jace](https://github.com/user-attachments/assets/19ac0c1e-aba2-48c6-b9c4-c58134d2fa27)

**Comment by andrewgioia** [comment]
I think this is good enough to get a trace and preliminary icon into 3.16.1 now.

**Comment by Emnalyeriar** [comment]
@andrewgioia any change get get this one added? :)
