### ISSUE TITLE
SCSS won't compile due to missing commas

### ISSUE THREAD

**Issue by jasonisme** [andrewgioia/Keyrune#25]
Lines 272-274 of _variables.scss
Change:
("Xbox Media Promo" 'pxbox', "\e915"),
  ("Magic Premiere Shop" 'pmps', "\e919"),
  ("Mirrodin Pure" 'pmpu', "\e91a"),

to 

  ("Xbox Media Promo", 'pxbox', "\e915"),
  ("Magic Premiere Shop", 'pmps', "\e919"),
  ("Mirrodin Pure", 'pmpu', "\e91a"),

**Comment by andrewgioia** [comment]
Whoops! Thanks @jasonisme I just pushed the fix for that.
