### ISSUE TITLE
Unofficial set symbols

### ISSUE THREAD

**Issue by andrewgioia** [andrewgioia/Keyrune#26]
We've received some requests for icons representing sets or collections of cards that have no official symbol or set code. I'm going to list them here and perhaps include a new section in the repo for "Unofficial symbols" that, while not ever used by Wizards and would need to be "custom," could be helpful for projects that need some way of uniquely distinguishing these cards.

[Editing this to be a checklist with update:]

- [x] **Collector's Edition** &mdash; blank core set icon with CE on it
- [x]  **International Collector's Edition** &mdash; blank core set icon with IE on it
- [x]  **Revised FBB / FWB** &mdash; kicking this, I don't think they need their own set symbols and agree with @csuhta on the use case
- [x]  **4th Edition Alternate** &mdash; while this is the same as above and I don't think this needs an alternate icon (they're still "4th Edition"), I'm going to make a 4th edition icon with an asterix for now and see if it's usable
- [x]  **Introductory Two-Player Set** &mdash; this seems extremely minor to create an icon for but "2PS" stylized the same way as MPS will work here
- [x]  **Pro Tour and World Cup** &mdash; these already have correct symbols in `pmei` and `parl` depending on the year
- [x]  **APAC and Euro lands** &mdash; still investigating
- [x]  **Anthologies** &mdash; this already has an icon in Keyrune
- [x]  **Judge Rewards** &mdash; see Pro Tour and World Cup, icons exist

**Comment by csuhta** [comment]
My two cents here:

- **Revised/4th Edition:** Set symbols aren't unique (especially for promos and alt printings). It's OK for two sets to have the same symbol. Sites are not going a good job if they only identify a set using the symbol without any other text nearby. 
- That said, **the proposed CE symbol and IE symbol would be awesome**, to mirror the other Alpha/Beta-related sets
- For the **Pro Tour, World Cup, and Judge rewards**, the correct set symbol is either the DCI oval or the Wizards shooting star, depending on the year of the cards were printed. You already have these symbols as `pmei` and `parl`. This is true for almost all promos before the Welcome Decks started getting symbols

**Comment by cybey** [comment]
For these unofficial icons, you could also consider the IDW media promos logo.

Example: [Standstill from IDW](http://www.abugames.com/images/products/promocards/standstill_idw.jpg)

**Comment by andrewgioia** [comment]
Updates underway; I created CE and IE icons and should have the 2PS and A4ED done today. I still need to figure out what to do for APAC and EURO lands.

**Comment by cybey** [comment]
Any intentions on doing FNM or IDW logo's?

Would love to be able to do it myself and help you out, but would need some pointers on how you create these logos and package them up in a font.

**Comment by andrewgioia** [comment]
@cybey Yes definitely, I forgot about IDW. I can add it in 3.0.1 this week. For FNM though, don't those cards use the original foil symbol (http://andrewgioia.github.io/Keyrune/icons.html?icon=pmei) of the shooting star? Is there a different set symbol for those cards?

If you happen to have a higher resolution source image on the IDW (and/or FNM) symbols that would be a huge help. I don't own any of these cards unfortunately and can't scan anything myself, but if not I can try to make do from scans online.

**Comment by andrewgioia** [comment]
Actually it's just the IDW logo and there are tons of high resolution versions of that. I should have this in soon.

**Comment by andrewgioia** [comment]
IDW is added in 3.0.1

**Comment by cybey** [comment]
Awesome.

For some reason I was under the impression that FNM had it's own logo, but it doesn't seem to be actually used on cards.
MagicCardMarket uses a logo similar to [this one](http://www.beyondcomics.com/wp-content/uploads/2011/07/FNM1.jpg).

**Comment by mediareason** [comment]
FNM used to be printed on some of the cards:

http://magiccards.info/fnmp/en/118.html

**Comment by andrewgioia** [comment]
@cybey @mediareason Closing this one out, the latest (3.1.5) has the FNM logo now!
