### ISSUE TITLE
[Request] Missing & wrong scale of icons

### ISSUE THREAD

**Issue by AchFilip** [andrewgioia/keyrune#260]
Hey, I downloaded the Set Symbol Icons from [here](https://keyrune.andrewgioia.com/icons.html?icon=ody) and I found that there are a couple of icons missing in the svg folder. Some of them are the Foundations and Aetherdrift.

Moreover, I found that the Duskmourn & Myster Booster 2 icons have a wrong scale and coloring in comparison with the other icons.

**Comment by andrewgioia** [comment]
Good catch, yeah those look like they were added outside of the normal process (i.e., from Icomoon's export). I'll make sure that gets fixed in the next release.
