### ISSUE TITLE
Archenemy vs Archenemy: Nicol Bolas

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#27]
Hi, I was looking at the two symbols and up until now I was thinking they should be identical. However the keyrunes are slightly different. Is there a reason for that?

**Comment by andrewgioia** [comment]
Thanks for the heads up @yandere-sliver, I didn't even realize it was the same symbol! Wow. 

I created the Archenemy: Nicol Bolas separately from the symbol on the WOTC Coming Soon page which probably accounts for the difference. I'm going to remove the second one so they're identical.

**Comment by andrewgioia** [comment]
Fixed in latest push!
