### ISSUE TITLE
Chain Lock Symbol

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#28]
There was one April Fools Joke which announced From the Vaults: Vaults.

They also showed a set symbol for the set which is a Chain Lock.

![chain_lock_symbol](https://cloud.githubusercontent.com/assets/25598912/23870179/e7f2f802-0825-11e7-9cc0-5828ae5e3d02.png)

**Comment by andrewgioia** [comment]
This one is also now live
