### ISSUE TITLE
Timeshifted Rarity

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#29]
I worked on timeshifted rarity a bit looks like this: https://mtg.gamepedia.com/User:Yanderesliver/sandbox

I put the following code in the mtg wiki css, not sure if you would want to add it to the project: 

.ss-time {
  color: #800080;
}
.ss-time.ss-grad {
  background: -webkit-gradient(linear, left top, right top, color-stop(1%, #800080), color-stop(50%, #D8BFD8), color-stop(100%, #800080));
  /* Chrome,Safari4+ */
  background: -webkit-linear-gradient(left, #800080 1%, #D8BFD8 50%, #800080 100%);
  -webkit-text-stroke: 0.03em #000;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
.ss-time.ss-grad.ss-no-border {
  -webkit-text-stroke: 0;
}

**Comment by andrewgioia** [comment]
Thanks @yandere-sliver I just pushed this up, looks great.
