### ISSUE TITLE
Update to latest in npm (currently 1.7.1)

### ISSUE THREAD

**Issue by Nightbr** [andrewgioia/Keyrune#30]
Hello,

I'm using npm (or yarn) to install keyrune but it seems to be not updated to the latest version of keyrune. Can you update to the latest version please on npm ?

I think you can create a webhook on github to synchronise npm repository and your repository in order to have the latest at each push.

Thanks for this amazing work!

<https://www.npmjs.com/package/keyrune>

**Comment by andrewgioia** [comment]
Sorry about that @Nightbr I just updated on NPM. I'll make sure to run `npm publish` each time I update as well.

You shouldn't need to but just more as an fyi it looks like you can change your NPM dependency to directly reference the Github project if you want to make extra sure you always get the latest (i.e., not go through the NPM registry but check from GH instead):

    "dependencies": {
        "keyrune": "andrewgioia/Keyrune"
    }

Thanks again for the heads up!
