### ISSUE TITLE
Fix Masterpiece Series: Kaladesh Inventions code

### ISSUE THREAD

**Issue by Nightbr** [andrewgioia/Keyrune#31]
Hi,

you set `mp1` for masterpiece series but it seems to be mps (according to [mtgjson](
https://github.com/mtgjson/mtgjson/issues/273)).

<https://api.magicthegathering.io/v1/sets?name=inventions>

![image](https://cloud.githubusercontent.com/assets/4228646/23909216/72be5d86-08d6-11e7-81fc-a31d1e17885a.png)

It should be great if we could create alias for icons (such as mp1, mps, ...) in order to be backward compatible (if someone already hardcoded mp1 for Kaladesh Invention for instance).

I can help on the SASS edit (make a PR) if you want.

**Comment by andrewgioia** [comment]
Thanks @Nightbr, I just pushed up a correction for this. I'm not sure where I had seen mp1, it could have been MODO but I couldn't find it anywhere looking just now. It's now .mps with a .mp1 alias still.
