### ISSUE TITLE
Amonkhet Invocations

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#33]
[The Invocation masterpieces](https://scryfall.com/search?q=%2B%2Be%3Amp2&order=spoiled) are being spoiled today. The symbol is a "handwritten" set of Bolas horns, best capture of it so far:

![aba9ev1y](https://cloud.githubusercontent.com/assets/769083/24430803/7a87a69c-13e6-11e7-9677-198b348f442a.png)

Also the set code still `MPS`, repeated from Kaladesh inventions. 🙄

**Comment by csuhta** [comment]
Here's a working draft:
[mp2.svg.zip](https://github.com/andrewgioia/Keyrune/files/880667/mp2.svg.zip)

**Comment by andrewgioia** [comment]
Thanks @csuhta awesome work. I appreciate you doing these so quickly as well. 

I just pushed up v2.2.2 including this and correcting/aliasing the Nemesis/Portal 2 codes.
