### ISSUE TITLE
Card Icons

### ISSUE THREAD

**Issue by owo** [andrewgioia/Keyrune#34]
Hi,

Are there any plans to add card icons such as mana-type, energy, tap, etc. ?
I guess it would be useful to add those for apps that want to a have consistent iconography.

Thanks :)

**Comment by owo** [comment]
Never mind, I found the Mana page :)

**Comment by andrewgioia** [comment]
No problem @owo glad you found it! For other's curious, the project is at https://github.com/andrewgioia/Mana
