### ISSUE TITLE
Welcome Deck 2017

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#35]
There are welcome decks again. Same pattern regarding set symbol and set code.

I have a youtube video were some of the cards are shown off: https://www.youtube.com/watch?v=ox1tXJUEQRw

**Comment by andrewgioia** [comment]
Thanks @yandere-sliver, I just put this up in the [latest release](https://github.com/andrewgioia/Keyrune/releases/tag/v2.2.3)
