### ISSUE TITLE
Add Hour of Devastation (HOU)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#38]
Symbol is a set of Bolas horns with no gem:

![hou_set_symbol](https://cloud.githubusercontent.com/assets/769083/25243365/caf2f104-25ca-11e7-8fa4-74978648fc4d.png)

http://magic.wizards.com/en/products/coming-soon

**Comment by csuhta** [comment]
Whoops, I didn't even notice this was already in there! https://andrewgioia.github.io/Keyrune/icons.html

**Comment by andrewgioia** [comment]
Thanks @csuhta, yeah I had some time this morning. It should be up on the CDN as well.
