### ISSUE TITLE
Trouble with the BRB symbol

### ISSUE THREAD

**Issue by gmac** [andrewgioia/Keyrune#41]
We've found that the BRB symbol is prone to breakage, most likely due to an unclosed path.

![screen shot 2017-05-16 at 10 06 22 am](https://cloud.githubusercontent.com/assets/727224/26110385/2f131880-3a20-11e7-8078-99e31ec2a9c6.png)

Fixed SVG markup:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><path d="M917.3 622.4c0-17.9 13.4-52.5 13.4-52.5l40.2-19v-40.3l-40.2-19s-13.4-34.6-13.4-52.5c0-17.8 13.4-77 107.2-81.5 0 0-76-107.2-205.5-107.2S582.3 313 526.4 415.7c0 0 86-63.7 201.1-63.7 87.1 0 112.8 58.1 112.8 88.2 0 30.2-25.7 63.6-93.9 63.6-68.1 0-108.3-22.3-108.3-22.3S628 505 544.3 505H49.5l-22.4-10-24.5 35.7 24.5 35.8 22.4-10.1h494.7c83.7 0 93.8 23.5 93.8 23.5s40.2-22.3 108.3-22.3c68.2 0 93.9 33.5 93.9 63.6 0 30.2-25.7 88.2-112.8 88.2-115.1 0-201.1-63.6-201.1-63.6C582.2 748.6 689.4 811.1 819 811.1s205.5-107.2 205.5-107.2c-93.8-4.5-107.2-63.7-107.2-81.5z"/></svg>
```

**Comment by andrewgioia** [comment]
Thanks for the info @gmac, I wasn't able to reproduce this but I think I fixed the path error. Are you able to pull down v3.0.2 and check for me?

**Comment by gmac** [comment]
Fabulous, worked perfectly. Thank you for the quick fix and for all of your effort on these beautiful icons! We're a huge fan of your work over at Scryfall.

**Comment by andrewgioia** [comment]
Awesome and thanks for the kind words @gmac!
