### ISSUE TITLE
Ixalan (XLN) and Rivals of Ixalan (RIX)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#45]
From Wizard's Play Network marketing materials:

![igjsce0tm04z](https://user-images.githubusercontent.com/769083/27231708-7cf0dd2a-5281-11e7-8a46-fb3de9dcb08a.png)

**Comment by csuhta** [comment]
Direct links to TIFF materials: 

- http://media.wizards.com/2017/wpn/marketingmaterials/en/xln/xln_logos.zip
- http://media.wizards.com/2017/wpn/marketingmaterials/en/rix/en_rix_logos.zip

**Comment by andrewgioia** [comment]
Thanks @csuhta! These and the others are now added in v3.1.1.
