### ISSUE TITLE
Unstable (UST)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#46]
From WPN marketing materials:

![lgxminbs](https://user-images.githubusercontent.com/769083/27231887-21d70152-5282-11e7-9817-66dc66ea0b1c.png)

Note that the official set code is `UST` despite the hashtag being `#MTGUN3`.

Direct links: http://media.wizards.com/2017/wpn/marketingmaterials/en/ust/ust_logos.zip

**Comment by andrewgioia** [comment]
Added in v3.1.1.
