### ISSUE TITLE
Explorers of Ixalan (E02)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#47]
From WPN marketing materials:

![mtge02_symbol_web-common](https://user-images.githubusercontent.com/769083/27231969-6b656f20-5282-11e7-8bcb-98c8cafaa8d5.png)

The set code is `E02` (with a zero)

Direct links: http://media.wizards.com/2017/wpn/marketingmaterials/en/e02/e02_logos.zip

**Comment by andrewgioia** [comment]
Added in v3.1.1.
