### ISSUE TITLE
Dragon Con (Nalathni Dragon) expansion symbol

### ISSUE THREAD

**Issue by linc** [andrewgioia/Keyrune#49]
There is a 1-off promo card from the 1994 Dragon Con named "Nalathni Dragon" that has a unique expansion symbol. I'm unable to find isolated artwork for it.

**Comment by andrewgioia** [comment]
Thanks @linc these are the largest images I could find on Google (admittedly a quick search):

* https://fr.magiccardmarket.eu/Cards/img/specimens/294868492.jpg
* https://vignette3.wikia.nocookie.net/cardguide/images/4/41/Nalathnidragon.jpg/revision/latest?cb=20130904083827

I'll keep looking around for something a bit clearer, these sources are unfortunately going to be tough to get the icon exact.

**Comment by linc** [comment]
I have a copy of the card if you want me to see how high-res I can capture it with my iPhone or scanner.

**Comment by linc** [comment]
![doc - jul 8 2017 - 1-33 pm](https://user-images.githubusercontent.com/117672/27987830-5f15c4ce-63e2-11e7-8138-98ccf97eef5e.jpg)

![img_9778](https://user-images.githubusercontent.com/117672/27987832-621635be-63e2-11e7-8c57-47b516e89e7d.JPG)

Unfortunately I think my ability to capture resolution vastly exceeds the fidelity of the printing back in the day.

**Comment by linc** [comment]
It appears to be based on the previous Dragon Con logo: http://wheeloftime.dragoncon.org/wp-content/uploads/2010/04/dc-logo.png

**Comment by andrewgioia** [comment]
@linc Thanks for the scans! I tried to trace it as best as I could and pushed up a new version (you can see the icon here: https://andrewgioia.github.io/Keyrune/icons.html?icon=pdgc). 

I couldn't figure out what was going on exactly at the bottom of the dragon but I think this version is 90% there. Let me know if you have any suggestions on cleaning it up or if this is good to close.

**Comment by linc** [comment]
Looks like a very reasonable interpretation to me. Thanks!
