### ISSUE TITLE
Iconic Masters

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#51]
The set symbol for IMA has been revealed:

![IMA symbol](http://magic.wizards.com/sites/mtg/files/images/featured/ima-icon.png)

(From the [coming soon](http://magic.wizards.com/en/products/coming-soon) page)

**Comment by andrewgioia** [comment]
[Iconic Masters](https://andrewgioia.github.io/Keyrune/icons.html?icon=ima) added in 3.1.4
