### ISSUE TITLE
Duel Decks: Merfolk vs. Goblins

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#52]
The set symbol for DDT has been revealed:

![DDT symbol](http://magic.wizards.com/sites/mtg/files/images/featured/pYjMLQueIm.png)

(From the [coming soon](http://magic.wizards.com/en/products/coming-soon) page)

**Comment by andrewgioia** [comment]
[Merfolk vs. Goblins](https://andrewgioia.github.io/Keyrune/icons.html?icon=ddt) added in 3.1.4
