### ISSUE TITLE
Commander 2017

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#53]
The set symbol for C17 has been revealed:

![C17 symbol](http://magic.wizards.com/sites/mtg/files/images/featured/c17-icon.png)

(From the [coming soon](http://magic.wizards.com/en/products/coming-soon) page)

**Comment by andrewgioia** [comment]
Thanks @fenhl, [Commander 2017](https://andrewgioia.github.io/Keyrune/icons.html?icon=c17) (and the others) has been added to the latest 3.1.4
