### ISSUE TITLE
Ability to request latest version from CDN

### ISSUE THREAD

**Issue by tdbear** [andrewgioia/Keyrune#54]
Providing a CDN was a major step in the right direction that removed a lot of hassles of upgrading to latest. However, currently in order to use the latest version of keyrune one needs to know the latest version. Since with keyrune most projects want to always use the latest version it would be nice to be able to request the latest version from CDN without caring about version. E.g. `?version=latest` or just omit the version parameter to indicate latest. Not sure if the CDN you use can support this.

Thank you for your amazing work!

**Comment by MartinKolarik** [comment]
The link provided in readme already points to the latest version: `//cdn.jsdelivr.net/npm/keyrune@latest/css/keyrune.css`

**Comment by tdbear** [comment]
My bad, thanks for pointing out.
