### ISSUE TITLE
Add Cheatpage to repo 

### ISSUE THREAD

**Issue by Xirious** [andrewgioia/Keyrune#57]
Hi there,

I believe it would be most beneficial to have Mana and Keyrune's cheatpages as an html in this repo as well. This way user's aren't required to visit an additional page for this. 

Alternative, making the documentation pages (for both) available as a separate repo would be good too.

**Comment by andrewgioia** [comment]
Hi @Xirious thanks for the suggestion, at this time I'm going to keep them separate as the docs don't need to be shipped with the source/dist for 99% of projects. The docs are a separate branch in this project (gh-pages) if that helps at all though.
