### ISSUE TITLE
Add Duelist magazine set symbol?

### ISSUE THREAD

**Issue by CharlesStover** [andrewgioia/Keyrune#58]
Just a request.

There is a pair of underwear that was used in the Duelist magazine to represent their fantasy cards.

[Example](https://www.magiclibrarities.net/629-7333-rarities-squee-triumphant-zoom-card.html#return)

Would love if this were accessible with the font. :)

**Comment by andrewgioia** [comment]
Haha! I've never seen this one before, yes we can/should definitely add it. I'll set a due date for this week.

**Comment by andrewgioia** [comment]
@CharlesStover this is added as of [version 3.1.7](https://github.com/andrewgioia/Keyrune/commit/2371e4a657b9a0ee55235a458655cd5b79229f52)!
