### ISSUE TITLE
Add Drake Stone set icon

### ISSUE THREAD

**Issue by CharlesStover** [andrewgioia/Keyrune#59]
Since the Duelist Magazine icon was accepted, I thought maybe the [Drake Stone](https://magic.wizards.com/en/articles/archive/feature/sorcerers-apprentice-2010-07-12) set symbol would be appreciated too.

I don't know if the set is called Drake Stone or The Sorcerer's Apprentice.

**Comment by andrewgioia** [comment]
Added in latest v3.1.8 https://github.com/andrewgioia/Keyrune/commit/09f19782bd19334f7361030f61b6bcbd8d5508ab
