### ISSUE TITLE
`ss-grad` adds `-webkit-text-stroke` which distorts some icons

### ISSUE THREAD

**Issue by randymorris** [andrewgioia/Keyrune#6]
It's mostly with set icons that have intricate details inside the icon, e.g. the core set icons.  Here's an example:

<img width="153" alt="screen shot 2016-06-11 at 2 12 29 pm" src="https://cloud.githubusercontent.com/assets/17761/15986764/91897a74-2fde-11e6-9a18-98fa0d397a95.png">

This example is showing the icons without `ss-grad`, with `ss-grad`, and with `ss-grad` and `-webkit-text-stroke: 0`.

Edit: This is on Chrome 53.0.2764.0 canary on OSX 10.11.4,

**Comment by andrewgioia** [comment]
Thanks @randymorris, for now I just added another class `.ss-no-border` if you want to override that border on any icon where it doesn't render well. I'll have to play around with a better solution to maintain on these complex icons. Feel free to submit a PR too if you find a nice way to implement it.
