### ISSUE TITLE
Sega Dreamcast set icon

### ISSUE THREAD

**Issue by CharlesStover** [andrewgioia/Keyrune#60]
On [these cards](https://deckmaster.info/set.php?shortcode=SDC) for the Dreamcast MTG game (much like Astral from MicroProse which is already supported).

**Comment by andrewgioia** [comment]
Added in latest v3.1.8 https://github.com/andrewgioia/Keyrune/commit/09f19782bd19334f7361030f61b6bcbd8d5508ab
