### ISSUE TITLE
Semi-official Alpha, Beta, Unlimited, Revised symbols

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#61]
Since MTGO has added the [Alpha Power 9 cards](https://www.cardhoarder.com/cards?data%5Bsets%5D%5B0%5D=1E) as possible event rewards, we've gotten a look at a possible official symbol for some early sets. It's incredibly plain, it's just a Pelagiad character inside a gradient box.

Here is a zip of LEA, LEB, 2ED, and 3ED symbols I drew from this: 
[lea-leb-2ed-3ed.zip](https://github.com/andrewgioia/Keyrune/files/1621184/lea-leb-2ed-3ed.zip)

![ss](https://user-images.githubusercontent.com/769083/34807892-30fc3c26-f659-11e7-933d-1becfd7eadc6.jpeg)

![ss3](https://user-images.githubusercontent.com/769083/34807916-4d0881e0-f659-11e7-8351-06c284a268b0.jpeg)

**Comment by fenhl** [comment]
These are the same symbols already used on Gatherer.

**Comment by yandere-sliver** [comment]
Currently there are already A, B, U, and R symbols for the keyrunes. I would wait till A25 before updating those symbols, because they want to put watermarks on every card. So that might give some additional confirmation on these set symbols.

**Comment by andrewgioia** [comment]
I agree with @yandere-sliver in waiting for A25 in a few weeks to see how Wizards handles it. I'm really hoping those ones you screenshot'ed aren't official though as they're pretty ugly 😕

**Comment by yandere-sliver** [comment]
The Alpha cards seem to have simply a Magic M watermark. 
https://magic.wizards.com/en/articles/archive/card-image-gallery/masters-25

Nothing which would help to differentiate the sets.

**Comment by yandere-sliver** [comment]
I looked at the cards again which are already in the font. To get the more official look you actually only need to remove the card left and right from the current A, B, U, R icons. So instead of showing the card fan you simply show the front cards.

**Comment by andrewgioia** [comment]
Finally got around to this, there are now Gatherer-official ABUR symbols in Keyrune as of 3.2.4. I used the versions that Gatherer has, for anyone interested here are the source PNGs and SVGs, and formatted SVGs for icons:

[PNGs.zip](https://github.com/andrewgioia/Keyrune/files/2225443/PNGs.zip)
[SVGs.zip](https://github.com/andrewgioia/Keyrune/files/2225444/SVGs.zip)
[Sized.zip](https://github.com/andrewgioia/Keyrune/files/2225446/Sized.zip)

I'm using the strange Gatherer set codes for these to differentiate them (1e, 2e, 2u, and 3e).
