### ISSUE TITLE
Masters 25 (A25)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#63]
Cards: https://scryfall.com/sets/a25?order=spoiled
Best picture of the symbol: 

<img width="269" alt="1hcdfhlv4u" src="https://user-images.githubusercontent.com/769083/35774034-1ffacb0e-0932-11e8-90a1-1087bb637251.png">

This one was really tricky: 

- The symbol on the cards does not match the symbol on the packaging. 
- The card symbol is the Planeswalker icon and "25" in the Beleren font, but both are edited/distorted
- Only the numerals of the "25" are colored for rarity, so they're knocked out of the overall shape

Here's my attempt at it: 
[a25.svg.zip](https://github.com/andrewgioia/Keyrune/files/1692463/a25.svg.zip)

**Comment by andrewgioia** [comment]
Thanks @csuhta and sorry for the delay here. I went to add this one and noticed that the WPN site now has an official A25 icon and used that one. Version 3.1.9 is live.
