### ISSUE TITLE
Dominaria and Commander Anthology 2

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#65]
They're not displayed on the product pages yet, but set symbols for [*Dominaria* (DOM)](https://magic.wizards.com/sites/mtg/files/images/featured/DOM_SYMBOL.png) and [*Commander Anthology 2* (CM2)](https://magic.wizards.com/sites/mtg/files/images/featured/CM2_SYMBOL.png) have appeared on the wizards.com servers.

**Comment by andrewgioia** [comment]
These are the only versions available with unfortunately low resolution:

![dom_symbol](https://user-images.githubusercontent.com/221473/36261279-dc0c92de-1231-11e8-90af-f86cce096f8f.png)
![cm2_symbol](https://user-images.githubusercontent.com/221473/36261280-dd9b2bec-1231-11e8-890a-dfc849c470de.png)

I'll take a crack at drawing them today and can update once the WPN website has higher res versions.

**Comment by andrewgioia** [comment]
These are added now as of version 3.2.0.
