### ISSUE TITLE
.ss-fw class does not work on scss version

### ISSUE THREAD

**Issue by pioz** [andrewgioia/Keyrune#67]
The `.ss-fw` class does not work on the scss version.
It set the font-size instead of the width.

Moreover `calc(18em / #{$keyrune_font_size})` is wrong because the right operand of `/` on the calc function must be a number (without units) https://developer.mozilla.org/en-US/docs/Web/CSS/calc. `$keyrune_font_size` is `14px` (with unit). So we need to remove the unit like this:

```
calc(18em / #{$keyrune_font_size / ($keyrune_font_size * 0 + 1)})
```

Last thing: `.ss-fw` class does not set the property `text-align: center;` like the css version.

**Comment by andrewgioia** [comment]
Thanks @pioz I just merged this in, I appreciate the help!
