### ISSUE TITLE
Signature Spellbook: Jace

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#69]
Icon is clear, but I can't find a high resolution version of that icon for the life of me.
https://magic.wizards.com/en/products/Signature-Spellbook-Jace
https://magic.wizards.com/en/articles/archive/news/signature-spellbook-jace-packaging-and-contents-2018-03-20

**Comment by yandere-sliver** [comment]
I found a good version:
http://mtgtrade.net/img/sets/ss1-r.gif

**Comment by fenhl** [comment]
This looks quite inaccurate. Gatherer source: <http://gatherer.wizards.com/Handlers/Image.ashx?type=symbol&set=SS1&size=large&rarity=C>

**Comment by csuhta** [comment]
Here's my attempt: 
[ss1.svg.zip](https://github.com/andrewgioia/Keyrune/files/2109494/ss1.svg.zip)

**Comment by andrewgioia** [comment]
Thanks @fenhl and @csuhta for your help again, I really appreciate it. Added in 3.2.2.
