### ISSUE TITLE
Request: Legendary Cube Symbol

### ISSUE THREAD

**Issue by joca-bt** [andrewgioia/Keyrune#7]
Hi, the legendary cube set symbol is pretty neat. Have you thought of adding it? http://magic.wizards.com/en/articles/archive/feature/worthy-legend-2015-11-10

**Comment by andrewgioia** [comment]
Nice I haven't seen that one, I can absolutely add it in. I'll shoot to have this up by Thursday.

**Comment by andrewgioia** [comment]
@joca-bt I just added this one, it should be good to go in master now.

**Comment by joca-bt** [comment]
Cool, thanks!
