### ISSUE TITLE
Battlebond (BBD)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#70]
From https://twitter.com/wizards_magic/status/992446241073221633
![dcxgmknu8aak_vn jpg-large](https://user-images.githubusercontent.com/769083/39642085-75b9fd50-4f9e-11e8-9555-4a579a0469cd.jpeg)

**Comment by csuhta** [comment]
Here's my attempt: 
[bbd.svg.zip](https://github.com/andrewgioia/Keyrune/files/1975473/bbd.svg.zip)

**Comment by andrewgioia** [comment]
Thanks! Added in 3.2.1 now.
