### ISSUE TITLE
Icons border quite big applying ss-grad style

### ISSUE THREAD

**Issue by asantalla** [andrewgioia/keyrune#72]
Hi! 

First of all, thanks for this awesome project.

I did some test and I noticed that some icons border are quite big when applying `ss-grad` style. For example:
![captura de pantalla 2018-05-14 a las 14 38 31](https://user-images.githubusercontent.com/612873/39997982-ebb8fb3a-5784-11e8-8335-4b93587fae7e.png)

For the previous example, I used the following CSS classes: `ss ss-m12 ss-4x ss-mythic ss-grad`

I think the main problem is the next line in the CSS file:
`-webkit-text-stroke: 0.03em #333;`

I tried with this line, changing the values with Chrome console, and it works better:
`-webkit-text-stroke: 0.015em #333;`

![captura de pantalla 2018-05-14 a las 14 44 05](https://user-images.githubusercontent.com/612873/39998093-4609e32e-5785-11e8-971b-04ea1a165e8b.png)

Is it a bug? Could you change it?

**Comment by asantalla** [comment]
Hi again,

probably the best option to solve this issue is:
`-webkit-text-stroke: 0.01em #333;`

As you can see in the following image:
![captura de pantalla 2018-05-14 a las 17 45 27](https://user-images.githubusercontent.com/612873/40008071-b6e9b4e8-579e-11e8-8ad7-cec20f465703.png)

Regards!

**Comment by andrewgioia** [comment]
This has been addressed somewhat in v3.16.1 upcoming, the unfortunate reality is that the lack of a true border glyph will prevent this from ever being perfect. Some set symbols do get a border glyph out of necessity, and in v4 every glyph will have one.
