### ISSUE TITLE
Global Series Jiang Yanggu & Mu Yanling (GS1)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#73]
Best images so far:

![en_0yulmb7hwf](https://user-images.githubusercontent.com/769083/40250583-b6b1c00c-5aa4-11e8-90ad-f711cf4e6728.png)
![en_gkszdcrlp9](https://user-images.githubusercontent.com/769083/40250584-b6c2d3c4-5aa4-11e8-8229-37e0b0330bfb.png)

**Comment by yandere-sliver** [comment]
Higher resolution: http://mtgtrade.net/img/sets/gs1-r.gif

**Comment by fenhl** [comment]
This looks quite inaccurate. Gatherer source: <http://gatherer.wizards.com/Handlers/Image.ashx?type=symbol&set=GS1&size=large&rarity=C>

**Comment by csuhta** [comment]
[gs1.svg.zip](https://github.com/andrewgioia/Keyrune/files/2109493/gs1.svg.zip)

**Comment by andrewgioia** [comment]
Added in 3.2.2
