### ISSUE TITLE
MTG Arena

### ISSUE THREAD

**Issue by fenhl** [andrewgioia/Keyrune#74]
As can be seen [here](https://pbs.twimg.com/media/Dh7amJxUYAA2rzB.jpg:large), MTG Arena now has some exclusive cards, with their own unique set symbol. The quality of these renders isn't the best, but the symbol appears to be the square-ish version of the MTG Arena logo which also appears on the loading screen.

**Comment by csuhta** [comment]
This appears to be the same icon they use for the application. Here's my SVG trace:
[mtga.svg.zip](https://github.com/andrewgioia/Keyrune/files/2191475/mtga.svg.zip)

**Comment by andrewgioia** [comment]
Added in 3.2.2
