### ISSUE TITLE
Commander 2018 (C18)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#75]
Here's an SVG:
[c18.svg.zip](https://github.com/andrewgioia/Keyrune/files/2222230/c18.svg.zip)

<img width="147" alt="rm69xin8h7" src="https://user-images.githubusercontent.com/769083/43120667-0a0a0db8-8ee9-11e8-8720-bf5c49110143.png">

**Comment by andrewgioia** [comment]
Thanks @csuhta! I made very minor tweeks based on a slightly higher resolution image posted today fwiw:

![c18](https://user-images.githubusercontent.com/221473/43163769-252f377a-8f5d-11e8-8212-9e0e72b53f5d.png)

As usual I'll update this once an official image is released on the product page or Gatherer.
