### ISSUE TITLE
Game Night (GNT)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#76]
Best image so far: 

![en_fl6ytg64pv](https://user-images.githubusercontent.com/769083/44696337-3268e280-aa45-11e8-9b8f-9285021ca96e.png)

More info: https://magic.wizards.com/en/articles/archive/news/introducing-magic-game-night-and-updated-gift-pack-2018-08-27

**Comment by csuhta** [comment]
Here's my attempt: 
[gnt.svg.zip](https://github.com/andrewgioia/Keyrune/files/2326313/gnt.svg.zip)

**Comment by andrewgioia** [comment]
Added in latest 3.3.0
