### ISSUE TITLE
Guild Kit (GK1)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#77]
This set will include symbols from each guild: https://scryfall.com/sets/gk1?order=spoiled

Perhaps you should consider pulling the guild symbols from https://andrewgioia.github.io/Mana/icons.html into this project?

**Comment by andrewgioia** [comment]
@csuhta Interesting, I didn't realize there was a separate code (GK1) using all of these guild symbols. 

I'm guessing we'll treat GK1 the same as Scryfall, using the GRN symbol. I can add these from Mana but am unsure what to refer to them as, just "golgari" etc or something like GK1_Golgari. Do you have a preference?

**Comment by yandere-sliver** [comment]
My suggestion would be simply to put in Golgari. When ever they make a GK2 or GK3 they will probably again use the Golgari symbol when they do a Golgari deck. So I think the symbol dis disconnected from the set code.

**Comment by andrewgioia** [comment]
Good point, that makes sense for future proofing. It's annoying that they overload GK1 with at least 6 different symbols but I don't think there's any other option. 

I wish they cared more about these symbol codes as well, things like their numbering system on certain sets like Guild Kits or Masters Editions only allows for 9 in a given series without having to completely redo the set code.

**Comment by csuhta** [comment]
IMO they don't need a special code assigned, just `ss-azorious` or similar

**Comment by andrewgioia** [comment]
These are added in 3.3.1 now. 

Somewhat unsurprisingly it looks like WOTC retouched almost all of the guild symbols again, this is the 3rd iteration now! I redid them and Keyrune now has these latest versions, I still need to update Mana though.
