### ISSUE TITLE
Guilds of Ravnica (GRN)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#78]
Best image so far:

![grn-273-impervious-greatwurm](https://user-images.githubusercontent.com/769083/44886145-af3ccc00-ac92-11e8-8c7b-80850cd4f3c6.jpg)

**Comment by csuhta** [comment]
Here's my trace based on this image:
https://i.redd.it/774u09l5urj11.jpg
[grn.svg.zip](https://github.com/andrewgioia/Keyrune/files/2343768/grn.svg.zip)

**Comment by cardsphere** [comment]
@andrewgioia do you think you can add GRN symbol? Please :-)

**Comment by NilsEnevoldsen** [comment]
Here they are from Gatherer.
![m](https://user-images.githubusercontent.com/222743/46231325-85320480-c339-11e8-885f-fc1e50cec1f5.png)
![r](https://user-images.githubusercontent.com/222743/46231326-85320480-c339-11e8-8dd3-1988c12bd400.png)
![u](https://user-images.githubusercontent.com/222743/46231327-85320480-c339-11e8-8ebf-72e3eab98b45.png)
![c](https://user-images.githubusercontent.com/222743/46231324-85320480-c339-11e8-8a34-c2cba755ddd0.png)

**Comment by andrewgioia** [comment]
@cardsphere @csuhta sorry about this and thank you for the source images/svg. I should have Keyrune updated tonight with this and the other newer symbols.

**Comment by andrewgioia** [comment]
Added in latest 3.3.0
