### ISSUE TITLE
Mythic Edition (MED)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#79]
Good images not available yet, but it has a unique set symbol.

Also a big warning that **they re-used the set code MED** for this set. It now collides with Masters Edition (MED) on MTGO. Scryfall moved Masters Edition to the ME1 set code.

![med-gr1-elspeth-knight-errant](https://user-images.githubusercontent.com/769083/44953028-68e69900-ae5b-11e8-9a64-3b0c77308b48.jpg)

**Comment by csuhta** [comment]
@andrewgioia Here's our trace: 
[med.svg.zip](https://github.com/andrewgioia/Keyrune/files/2407422/med.svg.zip)

**Comment by andrewgioia** [comment]
Thanks guys, I agree this is pretty irritating. Probably the biggest sin in this tiny little niche. 

I hate to break backwards compatibility but agree that moving the old MED to ME1, while not official, makes more sense now than introducing a new convention like MPS_MED.

**Comment by andrewgioia** [comment]
Added in latest 3.3.0
