### ISSUE TITLE
Contents missing when adding through npm

### ISSUE THREAD

**Issue by cybey** [andrewgioia/Keyrune#8]
I have a project where I am using both Keyrune and [Mana](https://github.com/andrewgioia/Mana). I've added both to my package.json like this:
>  "dependencies": {
>    "keyrune": "git+https://git@github.com/andrewgioia/Keyrune.git",
>    "mana": "git+https://git@github.com/andrewgioia/Mana.git"
>}

When I do a npm install, both folders get created in my node_modules as expected. However, the Mana package comes out fine, while in the Keyrune package files are missing. The only files that are available are package.json and README.md. There are no css, fonts or less folders.

**Comment by andrewgioia** [comment]
@cybey thanks for reporting this, I had incorrect paths on the `main` and `files` attributes in `package.json`. I removed files so that everything comes back now and fixed main, it should work but let me know if not.

**Comment by Takeno** [comment]
It seems to be corrected.

```
λ cat package.json 
{
  "dependencies": {
    "keyrune": "git+https://github.com/andrewgioia/Keyrune.git"
  }
}
```

```
λ tree node_modules/
node_modules/
└── keyrune
    ├── README.md
    ├── bower.json
    ├── css
    │   ├── keyrune.css
    │   └── keyrune.min.css
    ├── fonts
    │   ├── keyrune.eot
    │   ├── keyrune.svg
    │   ├── keyrune.ttf
    │   ├── keyrune.woff
    │   └── keyrune.woff2
    ├── index.html
    ├── less
    │   ├── border.less
    │   ├── core.less
    │   ├── icons.less
    │   ├── keyrune.less
    │   ├── path.less
    │   ├── rarities.less
    │   ├── sizes.less
    │   ├── variables.less
    │   └── width.less
    └── package.json
```

**Comment by cybey** [comment]
Seems fixed now.
Thanks
