### ISSUE TITLE
GRN icon broken?

### ISSUE THREAD

**Issue by cardsphere** [andrewgioia/Keyrune#81]
`<i class="ss ss-fw ss-grn ss-common"></i>` produces no icon. 
CSS is loaded from `http://cdn.jsdelivr.net/npm/keyrune@latest/css/keyrune.min.css` Font is loaded from `https://cdn.jsdelivr.net/npm/keyrune@latest/fonts/keyrune.woff2?v=3.3.0`.

`::before` correctly gets `.ss-gk1:before, .ss-grn:before { content: "\e94b"; }` applied. Does the font file have the glyph?

Thanks!

**Comment by cardsphere** [comment]
Not an issue anymore. Maybe CDN did not propagate fast enough?

**Comment by andrewgioia** [comment]
@cardsphere it very well could've been, I didn't update anything after that version so it's most likely on jsdelivr or some caching issue.
