### ISSUE TITLE
React / Vue Components

### ISSUE THREAD

**Issue by Saeris** [andrewgioia/keyrune#82]
Hey there! I created some simple React and Vue components around both Keyrune and Mana to make using both easier for users of those frameworks. Here are the links to all of them. Feel free to add them to the project documentation if you'd like!

React-Keyrune:
https://github.com/Saeris/react-keyrune
https://react-keyrune.saeris.io/

React-Mana:
https://github.com/Saeris/react-mana
https://react-mana.saeris.io/

Vue-Keyrune:
https://github.com/Saeris/vue-keyrune
https://vue-keyrune.saeris.io/

Vue-Mana:
https://github.com/Saeris/vue-mana
https://vue-mana.saeris.io/

For the Keyrune components, I'm using a feature of CSS Modules, the `:export{ }` syntax, to pull the values for the set names/codes straight from your SCSS variables. If you're interested in how I'm doing that, please take a look at [`src/keyrune.scss`](https://github.com/Saeris/react-keyrune/blob/master/src/keyrune.scss). It would be awesome if this functionality was baked into this project's CSS as well. That way others can easily pull the latest variables straight into their projects to be used programmatically. Doing something similar for Mana would be great as well. Right now I've got all the symbol names hard coded ([example here](https://github.com/Saeris/react-mana/blob/master/src/symbols.js)) which means I have to manually update that list every time a new symbol is added to the font. You'll notice I'm using nested objects to group symbols together, which aids in building out the demo page as well as categorize them to use in conditional checks. As both projects grow, adopting an approach like this make make the documentation easier to maintain.

While my time is limited, if you have any questions feel free to reach out! Thanks again for all your hard work maintaining these projects!

**Comment by andrewgioia** [comment]
Thank you for the contribution 🙏 Closing this for now.
