### ISSUE TITLE
Ultimate Box Topper (P/UMA)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#83]
Here's a trace! [puma.svg.zip](https://github.com/andrewgioia/Keyrune/files/2544404/puma.svg.zip)

The Scryfall team suspects this is a masterpiece set for an upcoming Masters set, so we chose the set code `puma`, reserving `uma`. That could change though.

![drbifzouuaan5s1](https://user-images.githubusercontent.com/769083/47944758-069a2b00-ded4-11e8-9653-4307ffaec256.png)

**Comment by yandere-sliver** [comment]
I would really like it if both codes could be used.

**Comment by yandere-sliver** [comment]
Just got confirmation it is the expansion symbol for Ultimate Masters and their Ultimate Box Topper, which is what this picture of Demonic Tutor is from.

**Comment by andrewgioia** [comment]
Thanks again @csuhta, you guys are fast. It looks like WPN released the high res vectors for it too: [[UMA] Ultimate Masters.zip](https://github.com/andrewgioia/Keyrune/files/2550804/UMA.Ultimate.Masters.zip)

I just updated to 3.3.2 with that symbol in there for UMA.
