### ISSUE TITLE
Readme jsdelivr.net links are missing "http:"

### ISSUE THREAD

**Issue by jlkatz** [andrewgioia/Keyrune#85]
Like title says, the CSS links don't work because they're missing "http:" at the beginning.  It took me a little while to figure out why I couldn't get even a basic example working =)

Current:
<link href="//cdn.jsdelivr.net/npm/keyrune@latest/css/keyrune.css" rel="stylesheet" type="text/css" />

Should be:
<link href="http://cdn.jsdelivr.net/npm/keyrune@latest/css/keyrune.css" rel="stylesheet" type="text/css" />

**Comment by andrewgioia** [comment]
Thanks @jlkatz, yes adding a scheme at the beginning will definitely work (e.g., `https://cdn....`). For reference though, the URLs in the readme are "scheme relative" and valid, they just pick up whatever scheme the site is currently using. Regardless if you're on https or http (or switching) these urls won't cause any issue as they'll just use the current one.

Here's a bit more if you're interested: https://stackoverflow.com/questions/3583103/network-path-reference-uri-scheme-relative-urls.

**Comment by jlkatz** [comment]
Thanks for the info!  I didn't know about this before now.
