### ISSUE TITLE
Printing uncommon or rare colored symbols appears as common (black)

### ISSUE THREAD

**Issue by jlkatz** [andrewgioia/keyrune#86]
For example, if you do a print-preview of the Samples page in either Chrome or Firefox, the Onslaught symbols for uncommon and rare look black.  The rare symbol has a slight tint of gold though.  The Mythic symbol looks perfect.  

![keyrune printing rarity symbols](https://user-images.githubusercontent.com/2244871/48502667-2ee32d00-e7e4-11e8-9757-f3cab6704c48.PNG)

**Comment by andrewgioia** [comment]
This has been resolved for a while, closing for now
