### ISSUE TITLE
Bower after  v3.1.1

### ISSUE THREAD

**Issue by marshl** [andrewgioia/Keyrune#89]
When I run `bower info keyrune` it says the latest available version is 3.1.1 (instead of 3.3.3), I assume that is because 3.1.1 was the last GitHub release made. Is bower still a supported usage method after 3.1.1 or should jsDelivr be used instead?

**Comment by andrewgioia** [comment]
Hi @marshl, sorry about this. I just created a release for the latest 3.4.0 which should now be good in Bower.

I think going forward I'm probably going to phase it out completely in favor of NPM and the public CDN, perhaps after about 6 months.
