### ISSUE TITLE
Publishing on NPM

### ISSUE THREAD

**Issue by arcanis** [andrewgioia/Keyrune#9]
This issue is both for Keyrune and Mana. Could it be possible to publish them on npm? It would help to keep the dependencies in line with the rest of the application (especially versionning), and wouldn't rely on your repository availability (its name could change, your account could be hijacked and malicious commits be issued, or the repository itself could even be taken down).

On a related note, it seems that the `keyrune` package name is currently available, but `mana` is already used, which means that we can't use both the official package and yours with npm. Publishing your packages on npm would prevent this issue from happening again (granted, you would need to rename them first into something like `mtg-keyrune` / `mtg-mana`).

**Comment by jordanbrauer** [comment]
I agree with this. I am starting a project and would like to use your package (credit will be given!). Unfortunate that it's not available through npm to easily maintain dependencies. :(

**Comment by andrewgioia** [comment]
@arcanis @jordanbrauer I just registered this at npm under `keyrune`, I haven't done this before and it seemed to have registered correctly but can someone test it out before I close this issue? Thanks.

**Comment by jordanbrauer** [comment]
@andrewgioia Just successfully installed the package as a dependency to my project. Can confirm it works. :)

**Comment by andrewgioia** [comment]
@jordanbrauer thanks for checking, I'll go ahead and do this for mana too then.
