### ISSUE TITLE
GK2 icon should match RNA

### ISSUE THREAD

**Issue by m3Ss1** [andrewgioia/Keyrune#91]
Similar to GRN/GK1
.ss-grn:before,
.ss-gk1:before {
  content: "\e94b";
}

The style of GK2 should be the same of RNA, for consistency with GRN/GK1.
.ss-rna:before,
**.ss-gk2:before** {
  content: "\e959";
}

**Comment by andrewgioia** [comment]
Thanks for the heads up! Added in 3.4.0.
