### ISSUE TITLE
Missing DOM, M19, GRN, RNA, WAR in the TTF

### ISSUE THREAD

**Issue by akarpodinis** [andrewgioia/Keyrune#94]
Title.  They're missing from the master ttf and from the latest release.

**Comment by andrewgioia** [comment]
@akarpodinis this should have been corrected last month with 3.4.1 but it's definitely correct now with 3.4.2. Since then I'm incrementing the font's version number on the font files themselves which has fixed this.

**Comment by akarpodinis** [comment]
Thanks for checking this out!

I downloaded and installed the TTF in the 3.4.2 zip and I don't see the missing symbols:

![fonts](https://user-images.githubusercontent.com/6482354/58115597-6e8e3580-7bc8-11e9-9319-1eadc236fa09.png)

**Comment by akarpodinis** [comment]
One more screenshot, the version that installed is listed as `3.4`.

![version](https://user-images.githubusercontent.com/6482354/58115792-d47abd00-7bc8-11e9-806f-e058d396bf31.png)

**Comment by fenhl** [comment]
I had the same issue (stuck on version 1.0) but removing the font family from Font Book and then reinstalling the new version fixed it. Version number is still 3.4 though.

**Comment by akarpodinis** [comment]
> removing the font family from Font Book and then reinstalling the new version fixed it.

I tried that and no dice.

**Comment by fenhl** [comment]
Your first screenshot seems to be on the overview tab instead of the glyph list.

**Comment by akarpodinis** [comment]
> Your first screenshot seems to be on the overview tab instead of the glyph list.

You're right.  All the glyphs appear to be there.  Thanks for pointing that out.
