### ISSUE TITLE
Magic 2020 (M20)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#95]
Here's an SVG: [m20.svg.zip](https://github.com/andrewgioia/Keyrune/files/3285555/m20.svg.zip)

Example image: https://user-images.githubusercontent.com/769083/59426796-17364c00-8da7-11e9-9462-8a614972c95d.png

**Comment by yandere-sliver** [comment]
Could we on this occasion also update the M19 symbol?

The border of the M19 symbol currently in use is closer to border of M15 and before. (see here: https://gamepedia.cursecdn.com/mtgsalvation_gamepedia/3/30/Core_Set_symbols.jpg?version=b2b7bcbb0db6740b764952e703297af8)

While @csuhta version is missing the outside border. I think it is overall much more closer to the current core set symbols as the current M19 one.

**Comment by Razviar** [comment]
Hey! Update on this issue would be very appreciated, since M20 set is already live in MTGA.

**Comment by ethanmick** [comment]
Would love this added too, thanks!

**Comment by andrewgioia** [comment]
Wow sorry everyone, M20 is now added and I corrected M19 to match what it should have been. Thanks @yandere-sliver for the heads up there.
