### ISSUE TITLE
ELD icon 

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#97]
![ELDC](https://user-images.githubusercontent.com/25598912/61814865-ebe05b80-ae40-11e9-870a-68e4a3f4dcad.png)
![tedlink](https://user-images.githubusercontent.com/25598912/61814871-f00c7900-ae40-11e9-97d2-eb5f6014192a.png)
We already have the icon for the next set. I currently haven no way to build the SVG, but the pictures have fairly decent quality.

**Comment by csuhta** [comment]
Here's our trace
[eld.svg.zip](https://github.com/andrewgioia/Keyrune/files/3433889/eld.svg.zip)

**Comment by andrewgioia** [comment]
Thanks guys, added in 3.5.0 just now
