### ISSUE TITLE
Commander 2019 (C19)

### ISSUE THREAD

**Issue by csuhta** [andrewgioia/Keyrune#98]
Trace: [c19.svg.zip](https://github.com/andrewgioia/Keyrune/files/3484417/c19.svg.zip)

![c19_alg_exp_rare](https://user-images.githubusercontent.com/769083/62749222-9eabde80-ba29-11e9-9ede-c07a719d5771.png)

**Comment by andrewgioia** [comment]
Thanks again @csuhta, also added in 3.5.0 now
